/** KINETIC: original full-game physics backend.
 * These class/method spellings are a compatibility boundary for LOAD BEARING,
 * not a dependency on Jolt. All integration, contacts and constraints execute
 * in our freestanding kernel.cpp. There is no fallback to a third-party engine.
 */
let compiled, nextPointer=1;
const kernelModules=new Map();let selectedInfo={};
export function selectedKernelInfo(){return {...selectedInfo};}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>mul(a,1/(Math.hypot(...a)||1));
const qmul=(a,b)=>[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]],rotate=(q,v)=>{const t=mul(cross(q,v),2);return add(v,add(mul(t,q[3]),cross(q,t)));},qinv=q=>[-q[0],-q[1],-q[2],q[3]];
const xyz=v=>[v.GetX(),v.GetY(),v.GetZ()],xyzw=v=>[v.GetX(),v.GetY(),v.GetZ(),v.GetW()];
const eye=[1,0,0,0,1,0,0,0,1],zeros=()=>Array(9).fill(0),matrixAdd=(a,b)=>a.map((v,i)=>v+b[i]);
const tensorOffset=(m,r)=>Array.from({length:9},(_,k)=>m*((Math.floor(k/3)===k%3?dot(r,r):0)-r[Math.floor(k/3)]*r[k%3]));
function tensorRotate(I,q){const axes=[[1,0,0],[0,1,0],[0,0,1]].map(v=>rotate(q,v));return Array.from({length:9},(_,k)=>axes.reduce((s,a,i)=>s+axes.reduce((t,b,j)=>t+a[Math.floor(k/3)]*I[i*3+j]*b[k%3],0),0));}
class Owned {constructor(){this.ptr=nextPointer++;} AddRef(){} Release(){} }
export class Vec3 extends Owned {constructor(x=0,y=0,z=0){super();this.Set(x,y,z);}GetX(){return this.x;}GetY(){return this.y;}GetZ(){return this.z;}Set(x,y,z){this.x=x;this.y=y;this.z=z;return this;}Length(){return Math.hypot(this.x,this.y,this.z);}LengthSq(){return this.x*this.x+this.y*this.y+this.z*this.z;}}
export class Quat extends Vec3 {constructor(x=0,y=0,z=0,w=1){super(x,y,z);this.w=w;}GetW(){return this.w;}Set(x,y,z,w=1){super.Set(x,y,z);this.w=w;return this;}sRotation(axis,angle){const a=unit(xyz(axis)),s=Math.sin(angle*.5);return new Quat(...mul(a,s),Math.cos(angle*.5));}sIdentity(){return new Quat();}}
class ReadVec {constructor(array,start,w=false){this.a=array;this.o=start;this.q=w;}GetX(){return this.a[this.o];}GetY(){return this.a[this.o+1];}GetZ(){return this.a[this.o+2];}GetW(){return this.q?this.a[this.o+3]:0;}Length(){return Math.hypot(this.GetX(),this.GetY(),this.GetZ());}LengthSq(){return this.GetX()**2+this.GetY()**2+this.GetZ()**2;}}
function hull(points){
 const vs=points.map(p=>[...p]);if(vs.length<4||vs.length>40)throw Error(`KINETIC: convex hull requires 4..40 vertices (got ${vs.length})`);
 const faces=[],edges=[];for(let i=0;i<vs.length;i++)for(let j=i+1;j<vs.length;j++)for(let k=j+1;k<vs.length;k++){
  let normal=cross(sub(vs[j],vs[i]),sub(vs[k],vs[i]));if(Math.hypot(...normal)<1e-8)continue;normal=unit(normal);let d=dot(normal,vs[i]),pos=false,neg=false;for(const v of vs){const e=dot(normal,v)-d;if(e>1e-5)pos=true;else if(e< -1e-5)neg=true;}if(pos&&neg)continue;if(pos){normal=mul(normal,-1);d=-d;}if(faces.some(f=>dot(f.n,normal)>.99999&&Math.abs(f.d-d)<1e-4))continue;
  const ids=vs.map((v,id)=>({v,id})).filter(({v})=>Math.abs(dot(normal,v)-d)<1e-4),center=ids.reduce((s,a)=>add(s,mul(a.v,1/ids.length)),[0,0,0]),u=unit(sub(ids[0].v,center)),v=cross(normal,u);ids.sort((a,b)=>Math.atan2(dot(sub(a.v,center),v),dot(sub(a.v,center),u))-Math.atan2(dot(sub(b.v,center),v),dot(sub(b.v,center),u)));
  faces.push({n:normal,d,ids:ids.map(a=>a.id)});
 }
 let volume=0,first=[0,0,0],raw=zeros();for(const face of faces){const ids=face.ids;for(let i=1;i+1<ids.length;i++){const a=vs[ids[0]],b=vs[ids[i]],c=vs[ids[i+1]],vol=dot(a,cross(b,c))/6;volume+=vol;first=add(first,mul(add(add(a,b),c),vol/4));const square=axis=>vol/10*(a[axis]**2+b[axis]**2+c[axis]**2+a[axis]*b[axis]+a[axis]*c[axis]+b[axis]*c[axis]);const product=(x,y)=>vol/20*(2*(a[x]*a[y]+b[x]*b[y]+c[x]*c[y])+a[x]*b[y]+a[y]*b[x]+a[x]*c[y]+a[y]*c[x]+b[x]*c[y]+b[y]*c[x]);const [x,y,z]=[square(0),square(1),square(2)],xy=-product(0,1),xz=-product(0,2),yz=-product(1,2);raw=matrixAdd(raw,[y+z,xy,xz,xy,x+z,yz,xz,yz,x+y]);}}
 if(!(volume>1e-10))throw Error('KINETIC: degenerate or nonconvex hull');const center=mul(first,1/volume),I=sub(raw,tensorOffset(volume,center)).map(n=>n/volume);
 for(const f of faces)for(let i=0;i<f.ids.length;i++){const e=unit(sub(vs[f.ids[(i+1)%f.ids.length]],vs[f.ids[i]]));if(!edges.some(x=>Math.abs(dot(x,e))>.99999))edges.push(e);}
 if(faces.length>48||edges.length>64)throw Error('KINETIC: hull plane/edge capacity exceeded');return {vs,faces,edges,volume,center,I};
}
class Shape extends Owned {constructor(primitives){super();this.primitives=primitives;this.massProperties=properties(primitives);this.native=new WeakMap();}GetCenterOfMass(){return new Vec3(...this.massProperties.center);}GetSubType(){return this.primitives[0]?.kind??0;}GetRadius(){return this.primitives[0].h[0];}GetMassProperties(){return {mMass:this.massProperties.mass};}}
function properties(parts){let total=0,center=[0,0,0];const entries=parts.map(p=>{let volume,c=[0,0,0],I=zeros();if(p.kind===0){const [x,y,z]=p.h.map(x=>x*2);volume=x*y*z;I=[(y*y+z*z)/12,0,0,0,(x*x+z*z)/12,0,0,0,(x*x+y*y)/12];}else if(p.kind===1){volume=4/3*Math.PI*p.h[0]**3;I=eye.map(v=>v*.4*p.h[0]**2);}else{({volume,center:c,I}=p.hull);if(p.cylinder){const {r,h}=p.cylinder;I=[(3*r*r+4*h*h)/12,0,0,0,r*r/2,0,0,0,(3*r*r+4*h*h)/12];}}const m=volume*(p.density??1000),pos=add(p.c,rotate(p.q,c));total+=m;center=add(center,mul(pos,m));return {m,c:pos,I:tensorRotate(I,p.q).map(v=>v*m)};});if(!(total>0))throw Error('KINETIC: shape mass must be positive');center=mul(center,1/total);let I=zeros();for(const e of entries)I=matrixAdd(I,matrixAdd(e.I,tensorOffset(e.m,sub(e.c,center))));return {mass:total,center,I:I.map(v=>v/total)};}
export class BoxShape extends Shape {constructor(half,_margin=0){super([{kind:0,h:xyz(half),c:[0,0,0],q:[0,0,0,1]}]);}}
export class SphereShape extends Shape {constructor(radius){if(!(Number.isFinite(radius)&&radius>0))throw Error('Invalid sphere radius');super([{kind:1,h:[radius,radius,radius],c:[0,0,0],q:[0,0,0,1]}]);}}
export class CylinderShape extends Shape {constructor(halfHeight,radius,_margin){const vs=[];for(const y of [-halfHeight,halfHeight])for(let i=0;i<16;i++){const a=i*2*Math.PI/16;vs.push([radius*Math.cos(a),y,radius*Math.sin(a)]);}super([{kind:3,h:[radius,halfHeight,radius],hull:hull(vs),c:[0,0,0],q:[0,0,0,1],cylinder:{r:radius,h:halfHeight}}]);}}
class ShapeResult extends Owned {constructor(shape,error){super();this.shape=shape;this.error=error;}IsValid(){return !!this.shape;}Get(){if(!this.shape)throw Error(this.error||'Invalid shape');return this.shape;}Clear(){this.shape=undefined;}}
export class BoxShapeSettings extends Owned {constructor(half,margin=0){super();this.half=xyz(half);this.margin=margin;this.mDensity=1000;}Create(){const shape=new BoxShape(new Vec3(...this.half),this.margin);shape.primitives[0].density=this.mDensity;shape.massProperties=properties(shape.primitives);return new ShapeResult(shape);}}
export class ConvexHullShapeSettings extends Owned {constructor(){super();this.mPoints={data:[],push_back:v=>this.mPoints.data.push(xyz(v))};}Create(){try{const h=hull(this.mPoints.data),bounds=[0,1,2].map(i=>Math.max(...h.vs.map(v=>Math.abs(v[i]))));return new ShapeResult(new Shape([{kind:2,h:bounds,hull:h,c:[0,0,0],q:[0,0,0,1]}]));}catch(e){return new ShapeResult(undefined,e.message);}}}
export class StaticCompoundShapeSettings extends Owned {constructor(){super();this.children=[];}AddShape(p,q,shape){const source=shape instanceof Shape?shape:shape.Create().Get();this.children.push({p:xyz(p),q:xyzw(q),shape:source});}Create(){const parts=this.children.flatMap(s=>s.shape.primitives.map(p=>({...p,c:add(s.p,rotate(s.q,p.c)),q:qmul(s.q,p.q)})));return new ShapeResult(new Shape(parts));}}
export class CapsuleShapeSettings extends Owned {constructor(half,radius){super();this.half=half;this.radius=radius;}Create(){const s=new Owned();s.half=this.half;s.radius=this.radius;return new ShapeResult(s);}}
class CollisionGroup {constructor(){this.filter=null;this.group=0;this.sub=0;}SetGroupFilter(f){this.filter=f;}SetGroupID(id){this.group=id;}SetSubGroupID(id){this.sub=id;}GetSubGroupID(){return this.sub;}GetGroupID(){return this.group;}}
export class GroupFilterTable extends Owned {constructor(capacity){super();this.capacity=capacity;this.worlds=new Set();this.disabled=new Set();}DisableCollision(a,b){const k=a<b?`${a}:${b}`:`${b}:${a}`;this.disabled.add(k);for(const w of this.worlds){const A=w.byGroup.get(a),B=w.byGroup.get(b);if(A&&B)w.k.collision_filter(A.id,B.id,1);}}EnableCollision(a,b){this.disabled.delete(a<b?`${a}:${b}`:`${b}:${a}`);for(const w of this.worlds){const A=w.byGroup.get(a),B=w.byGroup.get(b);if(A&&B)w.k.collision_filter(A.id,B.id,0);}}}
export class BodyCreationSettings extends Owned {constructor(shape,p,q,motion,layer){super();this.shape=shape;this.position=xyz(p);this.rotation=xyzw(q);this.motion=motion;this.layer=layer;this.mMassPropertiesOverride={mMass:shape.massProperties?.mass??1};this.mCollisionGroup=new CollisionGroup();this.mFriction=.55;this.mRestitution=.03;this.mLinearDamping=.08;this.mAngularDamping=.14;this.mAllowSleeping=true;this.mMotionQuality=0;}}
class BodyID {constructor(b){this.body=b;}GetIndex(){return this.body.id;}GetIndexAndSequenceNumber(){return this.body.id+this.body.generation*8192;}}
class Body extends Owned {
 constructor(world,settings,id){super();this.world=world;this.id=id;this.generation=world.serial++;this.settings=settings;this.group=settings.mCollisionGroup;this.state=new Float32Array(world.k.memory.buffer,world.k.body_ptr(id),32);this.position=new ReadVec(this.state,0);this.rotation=new ReadVec(this.state,3,true);this.linear=new ReadVec(this.state,7);this.angular=new ReadVec(this.state,10);this.com=new ReadVec(this.state,19);this.bounds={mMin:new ReadVec(this.state,13),mMax:new ReadVec(this.state,16)};this.nativeID=new BodyID(this);this.linearDamping=settings.mLinearDamping;this.angularDamping=settings.mAngularDamping;}
 GetID(){return this.nativeID;}GetShape(){return this.settings.shape;}GetPosition(){return this.position;}GetRotation(){return this.rotation;}GetLinearVelocity(){return this.linear;}GetAngularVelocity(){return this.angular;}GetCenterOfMassPosition(){return this.com;}GetWorldSpaceBounds(){return this.bounds;}GetCollisionGroup(){return this.group;}GetMotionType(){return this.state[23];}IsActive(){return !!this.state[22];}GetAllowSleeping(){return !!this.state[25];}GetMotionProperties(){return this;}
 SetLinearVelocity(v){this.world.k.body_velocity(this.id,...xyz(v),0);}SetAngularVelocity(v){this.world.k.body_velocity(this.id,...xyz(v),1);}AddForce(v){this.world.k.body_force(this.id,...xyz(v),0);}AddTorque(v){this.world.k.body_force(this.id,...xyz(v),1);}AddImpulse(v,p){this.world.k.body_impulse(this.id,...xyz(v),...(p?xyz(p):[0,0,0]),p?1:0);}SetFriction(v){this.world.k.body_option(this.id,0,v);}SetRestitution(v){this.world.k.body_option(this.id,1,v);}SetAllowSleeping(v){this.world.k.body_option(this.id,4,+v);}ResetSleepTimer(){this.world.k.body_option(this.id,10,0);}SetGravityFactor(v){this.world.k.body_option(this.id,5,v);}SetLinearDamping(v){this.linearDamping=v;this.world.k.body_option(this.id,2,v);}SetAngularDamping(v){this.angularDamping=v;this.world.k.body_option(this.id,3,v);}GetLinearDamping(){return this.linearDamping;}GetAngularDamping(){return this.angularDamping;}ScaleToMass(v){this.world.k.body_mass(this.id,v);}ResetForce(){this.world.k.body_option(this.id,8,0);}ResetTorque(){this.world.k.body_option(this.id,9,0);}GetInverseMass(){return this.GetMotionType()===2?1/this.state[24]:0;}
}
class Joint extends Owned {constructor(world,id,kind){super();this.world=world;this.id=id;this.kind=kind;this.state=new Float32Array(world.k.memory.buffer,world.k.joint_ptr(id),8);this.linear=new ReadVec(this.state,0);this.angular=new ReadVec(this.state,3);this.motor=0;this.target=0;}SetEnabled(v){this.world.k.joint_enable(this.id,+v);}GetTotalLambdaPosition(){return this.kind===2?this.state[6]:this.linear;}GetTotalLambdaRotation(){return this.angular;}SetRotationLimits(lo,hi){this.world.k.joint_limits(this.id,...xyz(lo),...xyz(hi));}SetMaxFriction(axis,f){this.world.k.joint_friction(this.id,axis,f);}SetMotorState(v){this.motor=v;this.world.k.joint_motor(this.id,v,this.target);}SetTargetAngularVelocity(v){this.target=v;this.world.k.joint_motor(this.id,this.motor,v);}GetMinDistance(){return this.minDistance??0;}GetMaxDistance(){return this.maxDistance??1;}GetSubType(){return this.kind;}SetConstraintPriority(){}GetConstraintPriority(){return 0;}}
class ConstraintSettings extends Owned {constructor(kind){super();this.kind=kind;this.mPoint1=this.mPosition1=new Vec3();this.mPoint2=this.mPosition2=new Vec3();this.mHingeAxis1=new Vec3(1,0,0);this.mHingeAxis2=new Vec3(1,0,0);this.mNormalAxis1=new Vec3(0,1,0);this.mNormalAxis2=new Vec3(0,1,0);this.mMotorSettings={mMinTorqueLimit:-1000,mMaxTorqueLimit:1000};this.mMinDistance=0;this.mMaxDistance=1;}MakeFixedAxis(){}Create(a,b){if(a.world!==b.world)throw Error('KINETIC: cross-world constraint');const world=a.world,id=world.k.joint_new(a.id,b.id,this.kind,...xyz(this.mPoint1),...xyz(this.mPoint2));world.check();const j=new Joint(world,id,this.kind);if(this.kind===2){world.k.joint_distance(id,this.mMinDistance,this.mMaxDistance);j.minDistance=this.mMinDistance;j.maxDistance=this.mMaxDistance;}if(this.kind===3)world.k.joint_hinge(id,...xyz(this.mHingeAxis1),...xyz(this.mHingeAxis2),this.mMotorSettings.mMinTorqueLimit,this.mMotorSettings.mMaxTorqueLimit);world.joints.add(j);return j;}}
export class PointConstraintSettings extends ConstraintSettings {constructor(){super(1);}}
export class SixDOFConstraintSettings extends ConstraintSettings {constructor(){super(0);}}
export class DistanceConstraintSettings extends ConstraintSettings {constructor(){super(2);}}
export class HingeConstraintSettings extends ConstraintSettings {constructor(){super(3);}}
export class WorldSettings extends Owned {constructor(){super();this.mMaxWorkerThreads=0;}}
export class StateRecorderImpl extends Owned {Rewind(){}}
export class KineticWorld extends Owned {
 constructor(settings){super();if(!compiled)throw Error('KINETIC is not loaded');this.instance=new WebAssembly.Instance(compiled,{});this.k=this.instance.exports;const mem=this.k.memory.buffer;this.k.__wasm_call_ctors();this.bodies=new Map();this.byGroup=new Map();this.joints=new Set();this.geometries=new WeakMap();this.shapes=new WeakMap();this.serial=1;this.gravity=new Vec3(0,-9.81,0);this.settings={mNumVelocitySteps:24,mNumPositionSteps:3};this.filters=settings;this.scratch=new Float32Array(mem,this.k.scratch_ptr(),512);}
 check(){const code=this.k.error();if(code)throw Error(`KINETIC kernel error ${code}: ${['','body capacity','joint capacity','shape capacity','primitive capacity','convex geometry capacity','contact capacity','non-finite simulation'][code]??'unknown'}`);}
 compileShape(shape){if(this.k.counts(3)+1>=16384||this.k.counts(4)+shape.primitives.length>=65536||this.k.geometry_count()+shape.primitives.length>=8192){this.k.compact_shapes();this.shapes=new WeakMap();this.geometries=new WeakMap();}let id=this.shapes.get(shape);if(id!==undefined)return id;const m=shape.massProperties;this.scratch.set(m.I,0);id=this.k.shape_new(...m.center);for(const p of shape.primitives){let g=-1;if(p.kind===2||p.kind===3){g=this.geometries.get(p.hull);if(g===undefined){g=this.k.geom_new();for(const v of p.hull.vs)this.k.geom_vertex(g,...v);for(const f of p.hull.faces)this.k.geom_face(g,...f.n,f.d);for(const e of p.hull.edges)this.k.geom_edge(g,...e);this.geometries.set(p.hull,g);}}this.k.shape_primitive(id,p.kind,g,...p.c,...p.q,...p.h);}this.check();this.shapes.set(shape,id);return id;}
 GetPhysicsSystem(){return this;}GetBodyInterface(){return this;}GetObjectVsBroadPhaseLayerFilter(){return this.filters.mObjectVsBroadPhaseLayerFilter;}GetObjectLayerPairFilter(){return this.filters.mObjectLayerPairFilter;}GetTempAllocator(){return null;}GetPhysicsSettings(){return {...this.settings};}SetPhysicsSettings(p){this.settings={...p};this.k.set_iterations(p.mNumVelocitySteps,p.mNumPositionSteps);}GetGravity(){return this.gravity;}SetGravity(v){this.gravity.Set(...xyz(v));this.k.set_gravity(...xyz(v));}
 CreateBody(s){const shape=this.compileShape(s.shape),mass=s.mMassPropertiesOverride.mMass,id=this.k.body_new(shape,...s.position,...s.rotation,mass,s.motion,s.mCollisionGroup.group,s.mCollisionGroup.filter?.ptr??0,s.layer);this.check();const body=new Body(this,s,id);this.bodies.set(id,body);this.byGroup.set(s.mCollisionGroup.sub,body);s.mCollisionGroup.filter?.worlds.add(this);for(const [opt,val] of [[0,s.mFriction],[1,s.mRestitution],[2,s.mLinearDamping],[3,s.mAngularDamping],[4,+s.mAllowSleeping],[6,s.mMotionQuality]])this.k.body_option(id,opt,val);return body;}
 AddBody(id,activate){this.k.body_added(id.body.id,1);if(!activate)this.k.body_option(id.body.id,11,0);}RemoveBody(id){this.k.body_added(id.body.id,0);}DestroyBody(id){this.k.body_destroy(id.body.id);this.bodies.delete(id.body.id);this.byGroup.delete(id.body.group.sub);}ActivateBody(id){this.k.body_option(id.body.id,10,0);}DeactivateBody(id){this.k.body_option(id.body.id,11,0);}
 SetPositionAndRotation(id,p,q,activate){this.k.body_pose(id.body.id,...xyz(p),...xyzw(q),+activate);}SetPosition(id,p,activate){this.SetPositionAndRotation(id,p,id.body.GetRotation(),activate);}SetRotation(id,q,activate){this.SetPositionAndRotation(id,id.body.GetPosition(),q,activate);}IsAdded(id){return !!id.body.state[26];}SetShape(id,shape,_mass,activate){id.body.settings.shape=shape;this.k.body_shape(id.body.id,this.compileShape(shape));if(activate)this.ActivateBody(id);}SetMotionType(id,type,activate){this.k.body_option(id.body.id,7,type);if(activate)this.ActivateBody(id);}MoveKinematic(id,p,q,dt){const body=id.body,d=mul(sub(xyz(p),xyz(body.GetPosition())),1/dt),rotation=qmul(xyzw(q),qinv(xyzw(body.GetRotation()))),sign=rotation[3]>=0?1:-1;body.SetLinearVelocity(new Vec3(...d));body.SetAngularVelocity(new Vec3(...mul(rotation.slice(0,3),2*sign/dt)));this.ActivateBody(id);}
 AddConstraint(c){c.SetEnabled(true);}RemoveConstraint(c){if(!this.joints.has(c))return;this.k.joint_remove(c.id);this.joints.delete(c);}WereBodiesInContact(a,b){return !!this.k.were_contact(a.body.id,b.body.id);}Step(dt,_steps){const err=this.k.step(dt);if(err)this.check();}
 GetNarrowPhaseQuery(){return this;}CastRay(ray,_settings,collector){const id=this.k.raycast(...xyz(ray.mOrigin),...xyz(ray.mDirection));collector.hit=id>=0?{mBodyID:this.bodies.get(id).GetID(),mFraction:this.scratch[0]}:null;}
 SaveState(recorder){recorder.signature=this.signature();recorder.bodyBytes=new Uint8Array(this.k.memory.buffer,this.k.state_start(),this.k.state_size()).slice();recorder.jointBytes=new Uint8Array(this.k.memory.buffer,this.k.joints_start(),this.k.joints_size()).slice();recorder.gravity=xyz(this.gravity);}
 RestoreState(recorder){if(!recorder.bodyBytes||recorder.signature!==this.signature())return false;new Uint8Array(this.k.memory.buffer,this.k.state_start(),this.k.state_size()).set(recorder.bodyBytes);new Uint8Array(this.k.memory.buffer,this.k.joints_start(),this.k.joints_size()).set(recorder.jointBytes);this.SetGravity(new Vec3(...recorder.gravity));return true;}
 signature(){return JSON.stringify([...this.bodies.values()].map(b=>[b.settings.shape.primitives.length,b.state[24],b.group.sub]))+JSON.stringify([...this.joints].map(j=>j.kind));}
 dispose(){for(const b of this.bodies.values())b.group.filter?.worlds.delete(this);this.bodies.clear();this.joints.clear();this.byGroup.clear();}
}
export class CharacterVirtualSettings extends Owned {constructor(){super();this.mShapeOffset=new Vec3();this.mUp=new Vec3(0,1,0);this.mMass=80;this.mMaxStrength=1000;this.mMaxSlopeAngle=Math.PI/3;}}
export class ExtendedUpdateSettings extends Owned {constructor(){super();this.mStickToFloorStepDown=new Vec3(0,-.3,0);this.mWalkStairsStepUp=new Vec3(0,.23,0);this.mWalkStairsStepDownExtra=new Vec3(0,-.02,0);}}
export class CharacterVirtual extends Owned {constructor(s,p,q,world){super();this.settings=s;this.world=world;this.position=new Vec3(...xyz(p));this.velocity=new Vec3();this.supported=false;this.ground=new Vec3();this.groundID=-1;}GetPosition(){return this.position;}SetPosition(p){this.position.Set(...xyz(p));this.supported=false;}GetLinearVelocity(){return this.velocity;}SetLinearVelocity(v){this.velocity.Set(...xyz(v));}IsSupported(){return this.supported;}GetGroundVelocity(){return this.ground;}UpdateGroundVelocity(){const body=this.world.bodies.get(this.groundID);if(body){const v=add(xyz(body.GetLinearVelocity()),cross(xyz(body.GetAngularVelocity()),sub(xyz(this.position),xyz(body.GetCenterOfMassPosition()))));this.ground.Set(...v);}else this.ground.Set(0,0,0);}ExtendedUpdate(dt,_g,settings){const k=this.world.k,s=this.settings;k.character_move(...xyz(this.position),...xyz(this.velocity),dt,s.mShape.radius,s.mShape.half,settings.mWalkStairsStepUp.GetY(),this.supported?1:0,s.mMass);const out=this.world.scratch;this.position.Set(out[0],out[1],out[2]);this.velocity.Set(out[3],out[4],out[5]);this.supported=!!out[6];this.groundID=out[7];this.UpdateGroundVelocity();}}
export class RRayCast extends Owned {constructor(origin,dir){super();this.mOrigin=new Vec3(...xyz(origin));this.mDirection=new Vec3(...xyz(dir));}}
export class CastRayClosestHitCollisionCollector extends Owned {Reset(){this.hit=null;}HadHit(){return !!this.hit;}get_mHit(){return this.hit;}}
class Empty extends Owned {}
class LayerPair extends Owned {constructor(n){super();this.n=n;this.pairs=new Set();}EnableCollision(a,b){this.pairs.add(`${Math.min(a,b)}:${Math.max(a,b)}`);}}
class BroadLayers extends Owned {MapObjectToBroadPhaseLayer(){}}
const API={Vec3,RVec3:Vec3,Quat,BoxShape,SphereShape,CylinderShape,BoxShapeSettings,ConvexHullShapeSettings,StaticCompoundShapeSettings,CapsuleShapeSettings,BodyCreationSettings,GroupFilterTable,PointConstraintSettings,SixDOFConstraintSettings,DistanceConstraintSettings,HingeConstraintSettings,PointConstraint:Joint,SixDOFConstraint:Joint,DistanceConstraint:Joint,HingeConstraint:Joint,JoltSettings:WorldSettings,JoltInterface:KineticWorld,StateRecorderImpl,CharacterVirtualSettings,CharacterVirtual,ExtendedUpdateSettings,RRayCast,CastRayClosestHitCollisionCollector,RayCastSettings:Empty,BodyFilter:Empty,ShapeFilter:Empty,DefaultBroadPhaseLayerFilter:Empty,DefaultObjectLayerFilter:Empty,ObjectLayerPairFilterTable:LayerPair,BroadPhaseLayerInterfaceTable:BroadLayers,BroadPhaseLayer:Empty,ObjectVsBroadPhaseLayerFilterTable:Empty,EActivation_Activate:1,EActivation_DontActivate:0,EMotionType_Static:0,EMotionType_Kinematic:1,EMotionType_Dynamic:2,EMotionQuality_LinearCast:1,EMotorState_Off:0,EMotorState_Velocity:1,EOverrideMassProperties_CalculateInertia:1,castObject:o=>o,getPointer:o=>o?.ptr??0,destroy:o=>o?.dispose?.(),EShapeSubType_ConvexHull:2,engineName:'KINETIC — own C++/WASM',engineVersion:'0.2.0'};
export default async function loadOwnPhysics(options={}){
 const variant=options.variant==='reference'?'reference':'optimized';
 let entry=kernelModules.get(variant);
 if(!entry){
  let data=options.wasmBinary??(variant==='reference'?globalThis.__KINETIC_WASM_REFERENCE__:globalThis.__KINETIC_WASM__);
  if(!data){const url=variant==='reference'?new URL('./kernel-reference.wasm',import.meta.url):new URL('./kernel.wasm',import.meta.url);const response=await fetch(url);if(!response.ok)throw Error(`KINETIC WASM load failed: ${response.status}`);data=await response.arrayBuffer();}
  const module=await WebAssembly.compile(data);if(WebAssembly.Module.imports(module).length)throw Error('Unexpected dependency in own physics kernel');
  const digest=globalThis.crypto?.subtle?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),n=>n.toString(16).padStart(2,'0')).join(''):null;
  entry={module,variant,sha256:digest,wasmBytes:data.byteLength};kernelModules.set(variant,entry);
 }
 compiled=entry.module;selectedInfo={variant:entry.variant,sha256:entry.sha256,wasmBytes:entry.wasmBytes,thirdPartyPhysics:false};return API;
}
export const math={add,sub,mul,dot,cross,unit,rotate,qmul,qinv,hull,properties};
