import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
 await p.goto(process.env.TEST_URL||'http://localhost:5174');await p.waitForFunction(()=>window.__loadBearing?.demo?.active);
 const saved=await p.evaluate(()=>JSON.stringify(window.__loadBearing.pieces));
 await p.waitForFunction(()=>window.__loadBearing.demo.phase===0&&window.__loadBearing.demo.elapsed>8,{},{timeout:45000});const blast=await p.evaluate(()=>({shots:window.__loadBearing.demo.projectiles,fragments:window.__loadBearing.demo.fragments}));assert.ok(blast.shots>2&&blast.fragments>0,JSON.stringify(blast));await p.screenshot({path:'artifacts/demo-bombard.png'});console.log('bombard',blast);
 await p.waitForFunction(()=>window.__loadBearing.demo.phase===1&&window.__loadBearing.demo.elapsed>13,{},{timeout:55000});const car=await p.evaluate(()=>{const d=window.__loadBearing.demo,i=d.items.find(i=>i.kind==='vehicle-chassis'),p=i.body.GetPosition();return {x:p.GetX(),z:p.GetZ(),shots:d.projectiles,fragments:d.fragments}});console.log('car',car);assert.ok(Math.hypot(car.x,car.z-20)>5&&car.shots>4);assert.ok(car.fragments>0);await p.screenshot({path:'artifacts/demo-driving.png'});
 await p.click('#demo-skip');assert.equal(await p.evaluate(()=>JSON.stringify(window.__loadBearing.pieces)),saved);assert.ok(!await p.evaluate(()=>window.__loadBearing.demo.active));await p.reload();await p.waitForFunction(()=>window.__loadBearing?.ready);assert.ok(!await p.evaluate(()=>window.__loadBearing.demo.active));
 await p.click('#sandbox-mode');await p.click('[data-sandbox-tab=projectiles]');await p.locator('#projectile-mass').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('f');await p.waitForFunction(()=>window.__loadBearing.simulation?.projectiles>0);const n=await p.evaluate(()=>window.__loadBearing.simulation.projectiles);await p.locator('#projectile-speed').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('f');await p.waitForFunction(n=>window.__loadBearing.simulation.projectiles>n,n);console.log('PASS slider-focused F fires');
 await p.click('.primary-modes #show-demo');await p.waitForFunction(()=>window.__loadBearing.demo.active);await p.keyboard.press('Escape');await p.waitForFunction(()=>!window.__loadBearing.demo.active);assert.deepEqual(errors,[]);console.log('PASS first-visit demo, both live scenes, car movement/firing, skip/reload/replay and blueprint preservation');
}finally{await b.close()}
