import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
if(process.env.WEBGL)await page.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));
try{await page.addInitScript(()=>{localStorage.setItem('loadbearing.demo-seen','1');localStorage.setItem('loadbearing.last-mode',JSON.stringify({challengeId:'sandbox-demolition-yard'}));});await page.goto(process.env.TEST_URL||'http://localhost:5174');await page.locator('#boot-screen').waitFor({state:'detached'});await page.mouse.move(750,350);await page.keyboard.press('f');await page.waitForFunction(()=>window.__loadBearing.simulation?.elapsed>.3);
await page.evaluate(()=>{const d=window.__loadBearing;for(const item of d.simulation.items.filter(i=>i.kind==='column').slice(0,8)){const p=item.body.GetPosition();d.simulation.launchProjectile([p.GetX(),p.GetY()+7,p.GetZ()],[0,-85,0],25000,.9);}});
await page.waitForFunction(()=>window.__loadBearing.simulation.fragments>0,{},{timeout:30000});await page.waitForTimeout(450);await page.locator('#run').click();await page.mouse.move(15,15);await page.screenshot({path:'artifacts/physical-debris-only.png'});console.log(await page.evaluate(()=>({audio:window.__loadBearing.scene.audio.stats,backend:window.__loadBearing.scene.rendererBackend})));
assert.ok(await page.evaluate(()=>{const s=window.__loadBearing.scene;return !s.dust&&!s.debris&&s.fragmentBatches.refs.size>0}));
await page.click('#open-options');await page.evaluate(()=>{const a=window.__loadBearing.scene.audio;window.soundMeter=a.context.createAnalyser();a.master.connect(window.soundMeter);});await page.click('#game-options-sound-test');const peak=await page.evaluate(async()=>{const a=window.soundMeter,data=new Float32Array(a.fftSize);let peak=0;for(let i=0;i<10;i++){a.getFloatTimeDomainData(data);for(const v of data)peak=Math.max(peak,Math.abs(v));await new Promise(r=>setTimeout(r,12));}a.disconnect();return peak;});assert.ok(peak>.0001,'test sound must produce a measurable audio signal');console.log({audioPeak:peak});await page.uncheck('#game-options-sound');await page.locator('#game-options-volume').fill('0.2');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__loadBearing.scene.audio.enabled),false);await page.click('#restart');await page.waitForFunction(()=>window.__loadBearing.simulation.fragments===0);await page.reload();await page.locator('#boot-screen').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>window.__loadBearing.scene.audio.enabled),false);assert.equal(await page.evaluate(()=>window.__loadBearing.scene.audio.volume),.2);assert.deepEqual(errors,[]);console.log('PASS physical fragments without dust or sparks, fracture audio, reset and sound preferences');
}catch(e){console.log(errors);throw e;}finally{await browser.close()}

