import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const cdp=await p.context().newCDPSession(p);const touch=(type,pts)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:pts.map(([id,x,y])=>({id,x,y,radiusX:4,radiusY:4,force:1}))});
const center=async sel=>{const r=await p.locator(sel).boundingBox();return [r.x+r.width/2,r.y+r.height/2]};
const tap=sel=>p.locator(sel).tap();const count=()=>p.evaluate(()=>window.__loadBearing.pieces.length);
const bounds=async()=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);};
try{
 await p.addInitScript(()=>{for(const key of ['loadbearing','loadbearing-lab']){localStorage.setItem(key+'.demo-seen','1');localStorage.setItem(key+'.last-mode',JSON.stringify({challengeId:'sandbox-demolition-yard'}));}});await p.goto(process.env.TEST_URL||'http://localhost:5174');await p.locator('#boot-screen').waitFor({state:'detached'});await bounds();assert.ok(await p.locator('body').evaluate(e=>e.classList.contains('mobile-ui')));
 await tap('#mobile-help');await tap('#mobile-camera');await p.locator('#hover-help').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>window.__loadBearing.simulation),null,'help must not fire');
 await tap('#toggle-panels');await tap('[data-sandbox-tab=build]');await tap('[data-part=column]');assert.ok(!await p.locator('.sidebar').isVisible());
 const n=await count();await touch('touchStart',[[1,210,320]]);await touch('touchMove',[[1,270,360]]);await touch('touchEnd',[]);assert.equal(await count(),n,'drag must not place');
 await touch('touchStart',[[1,140,350],[2,260,350]]);await touch('touchMove',[[1,110,330],[2,285,360]]);await touch('touchEnd',[]);assert.equal(await count(),n,'pinch must not place');
 await p.waitForTimeout(700);const point=await p.evaluate(()=>{const d=window.__loadBearing,s=d.scene,r=s.container.getBoundingClientRect();for(let x=-8;x<=8;x+=2)for(let z=-8;z<=8;z+=2){if(d.pieces.some(p=>p.kind==='column'&&p.p[0]===x&&p.p[1]===0&&p.p[2]===z))continue;const v=s.camera.position.clone().set(x,0,z).project(s.camera),px=r.x+(v.x+1)*r.width/2,py=r.y+(1-v.y)*r.height/2;if(px>30&&px<360&&py>190&&py<620)return [px,py];}throw Error('no visible free placement point');});await p.touchscreen.tap(...point);assert.equal(await count(),n);await tap('#mobile-place');assert.equal(await count(),n+1);await tap('#undo');assert.equal(await count(),n);await tap('#select-tool');await p.screenshot({path:'artifacts/mobile-build-final.png'});console.log('PASS touch help, drag/pinch safety, preview/confirm placement and undo');
 await p.selectOption('#mobile-mode','sandbox-mode');await p.touchscreen.tap(190,330);await p.waitForFunction(()=>window.__loadBearing.simulation?.projectiles>0);await tap('#restart');await p.waitForFunction(()=>window.__loadBearing.simulation?.projectiles===0);await tap('#stop');
 await p.selectOption('#mobile-mode','vehicle-mode');await p.selectOption('#vehicle-level','1');await tap('[data-vehicle-part=engine]');const vp=await p.evaluate(()=>{const v=window.__loadBearing.vehicleWorkshop,r=v.renderer.domElement.getBoundingClientRect(),x=v.camera.position.clone().set(1,1.8,1).project(v.camera);return[r.x+(x.x+1)*r.width/2,r.y+(1-x.y)*r.height/2]});const before=await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.parts.length);await p.touchscreen.tap(...vp);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.parts.length),before+1);await tap('#mobile-vehicle-erase');await p.touchscreen.tap(...vp);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.parts.length),before);await p.screenshot({path:'artifacts/mobile-workshop-final.png'});
 await tap('#vehicle-drive');await p.waitForFunction(()=>window.__loadBearing.vehicleWorkshop.driving);await p.locator('#mobile-drive').waitFor({state:'visible'});await p.screenshot({path:'artifacts/mobile-driving.png'});
 const [sx,sy]=await center('.touch-stick'),[fx,fy]=await center('#mobile-cannon');const yaw=await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.yaw);
 await touch('touchStart',[[1,sx,sy-25]]);await touch('touchStart',[[1,sx,sy-25],[2,250,340]]);await touch('touchMove',[[1,sx+12,sy-25],[2,290,360]]);await touch('touchStart',[[1,sx+12,sy-25],[2,290,360],[3,fx,fy]]);await p.waitForTimeout(1500);
 assert.ok(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.touch.throttle>.3));assert.notEqual(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.yaw),yaw);await p.waitForFunction(()=>window.__loadBearing.simulation.projectiles>0);assert.equal(await p.evaluate(()=>document.pointerLockElement),null);await touch('touchEnd',[]);await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.touch.throttle),0);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.touch.fire),false);
 await touch('touchStart',[[1,sx,sy-25]]);await touch('touchCancel',[]);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.touch.throttle),0);await tap('#mobile-drive-reset');await p.waitForFunction(()=>window.__loadBearing.vehicleWorkshop.driving&&window.__loadBearing.simulation.elapsed<1);console.log('PASS vehicle touch placement/removal, simultaneous analog drive/look/fire, cancellation, world reset');
 await p.setViewportSize({width:844,height:390});await p.waitForTimeout(250);await p.screenshot({path:'artifacts/mobile-driving-landscape.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),844);await tap('#vehicle-return');await p.screenshot({path:'artifacts/mobile-workshop-landscape.png'});await p.locator('#vehicle-close').tap();await p.selectOption('#mobile-mode','campaign-mode');await p.screenshot({path:'artifacts/mobile-campaign-landscape.png'});await p.locator('#campaign-close').tap();await p.selectOption('#mobile-mode','show-demo');await p.waitForFunction(()=>window.__loadBearing.demo.active);await tap('#demo-skip');assert.deepEqual(errors,[]);console.log('PASS landscape layout, campaign, demo and no page errors');
}finally{await b.close();}
