import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true}),p=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
 await p.addInitScript(()=>{localStorage.setItem('loadbearing.demo-seen','1');localStorage.setItem('loadbearing-lab.demo-seen','1');});
 await p.goto(process.env.TEST_URL||'http://localhost:5174');await p.locator('#boot-screen').waitFor({state:'detached'});
 await p.click('#open-options');await p.selectOption('#game-options-resolution','0.75');await p.check('#game-options-invert');await p.uncheck('#game-options-hints');await p.keyboard.press('Escape');await p.reload();await p.locator('#boot-screen').waitFor({state:'detached'});assert.ok(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.invertMouseY));assert.ok(await p.locator('body').evaluate(e=>e.classList.contains('hide-game-hints')));await p.click('#open-options');assert.equal(await p.locator('#game-options-resolution').inputValue(),'0.75');await p.keyboard.press('Escape');
 await p.click('#vehicle-mode');await p.selectOption('#vehicle-level','1');await p.click('[data-vehicle-part=engine]');
 const point=await p.evaluate(()=>{const v=window.__loadBearing.vehicleWorkshop,rect=v.renderer.domElement.getBoundingClientRect(),position=v.camera.position.clone().set(1,1.8,1).project(v.camera);return{x:rect.x+(position.x+1)*rect.width/2,y:rect.y+(1-position.y)*rect.height/2};});
 await p.mouse.click(point.x,point.y);assert.ok(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.parts.some(p=>p.kind==='engine'&&p.p[0]===1&&p.p[1]===1.8&&p.p[2]===1)),'direct 3D part placement');
 await p.click('#vehicle-drive');await p.waitForFunction(()=>window.__loadBearing.vehicleWorkshop.driving);assert.equal(await p.locator('body').getAttribute('data-game-state'),'drive');assert.ok((await p.locator('#viewport').boundingBox()).height>700);
 await p.locator('#damage-stats').waitFor({state:'visible'});await p.waitForFunction(()=>document.getElementById('damage-stats').textContent.includes('Trümmer'));await p.screenshot({path:'artifacts/ui-drive-stats.png'});
 await p.click('.drive-options');const yaw=await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.yaw);await p.keyboard.press('f');await p.keyboard.press('w');assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.keys.size),0);assert.equal(await p.evaluate(()=>window.__loadBearing.vehicleWorkshop.yaw),yaw);await p.keyboard.press('Escape');
 await p.click('#world-controls');await p.click('[data-sandbox-tab=disasters]');await p.click('[data-hazard=wind]');await p.click('[data-hazard=flood]');await p.waitForFunction(()=>window.__loadBearing.simulation.sandboxHazards.wind&&window.__loadBearing.simulation.sandboxHazards.flood);await p.click('#restart');await p.waitForFunction(()=>window.__loadBearing.vehicleWorkshop.driving&&window.__loadBearing.simulation.elapsed<1);
 await p.click('#vehicle-return');await p.click('#vehicle-close');await p.click('#campaign-mode');await p.click('#level-preview-start');await p.click('#run');await p.waitForFunction(()=>window.__loadBearing.simulation?.elapsed>.2);assert.equal(await p.locator('body').getAttribute('data-game-state'),'test');assert.equal(await p.locator('.sidebar').isVisible(),false);await p.screenshot({path:'artifacts/ui-test.png'});await p.click('#stop');assert.equal(await p.locator('body').getAttribute('data-game-state'),'build');
 await p.setViewportSize({width:1024,height:768});await p.screenshot({path:'artifacts/ui-compact.png'});assert.ok((await p.locator('#run').boundingBox()).x<1024);assert.deepEqual(errors,[]);console.log('PASS options persistence, 3D vehicle placement, drive/modal input, simultaneous hazards, reset, campaign test/edit, compact viewport');
}finally{await browser.close()}

