import { chromium } from '@playwright/test';
import { mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

await mkdir('artifacts',{recursive:true});
const cache=path.join(process.env.LOCALAPPDATA??'', 'ms-playwright');
const installed=(await readdir(cache)).filter(n=>n.startsWith('chromium-')).sort();
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE??path.join(cache,installed.at(-1),'chrome-win','chrome.exe'),headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1536,height:960},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')console.log('BROWSER:',m.text())});
try {
 await page.goto(process.env.TEST_URL??'http://127.0.0.1:5173');
 await page.waitForFunction(()=>window.__loadBearing?.ready,{timeout:30000});
 await page.click('#workshop-mode');
 await page.screenshot({path:'artifacts/bridge-workshop.png'});
 console.log('Initial:',await page.locator('#count').textContent(),'elements;',await page.locator('#engine-label').textContent());
 const initial=Number(await page.locator('#count').textContent());
 await page.click('#clear');assert.equal(await page.locator('#count').textContent(),'0');
 await page.click('#undo');assert.equal(Number(await page.locator('#count').textContent()),initial);
 await page.click('#clear');await page.click('#save');await page.reload();await page.waitForFunction(()=>window.__loadBearing?.ready);await page.click('#workshop-mode');assert.equal(await page.locator('#count').textContent(),'0','saved blueprint should survive a reload');await page.click('#reference');
 await page.click('[data-part="column"]');
 await page.click('#level-up');assert.equal(await page.locator('#level-value').textContent(),'4 m');
 const screen=await page.evaluate(()=>{const s=window.__loadBearing.scene;const v=s.camera.position.clone().set(0,4,8).project(s.camera);const r=s.container.getBoundingClientRect();return {x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2}});
 await page.mouse.click(screen.x,screen.y);
 assert.equal(Number(await page.locator('#count').textContent()),initial+1);
 await page.keyboard.press('Escape');
 await page.click('#undo');assert.equal(Number(await page.locator('#count').textContent()),initial);
 await page.click('#help');assert.equal(await page.locator('#help-dialog').evaluate(d=>d.open),true);await page.click('#help-close');
 await page.click('#disaster-mode');assert.equal(await page.locator('#scenario').inputValue(),'landslide');
 await page.screenshot({path:'artifacts/retaining-wall.png'});
 await page.click('#run');
 await page.waitForFunction(()=>window.__loadBearing.simulation?.elapsed>.5);
 await page.click('#run');const time=await page.evaluate(()=>window.__loadBearing.simulation.elapsed);
 await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__loadBearing.simulation.elapsed),time);
 await page.click('#run');await page.waitForFunction(()=>window.__loadBearing.simulation?.rocks>=3);
 await page.screenshot({path:'artifacts/landslide-test.png'});
 await page.click('#stop');assert.equal(await page.locator('#status').textContent(),'EDIT MODE');
 await page.selectOption('#scenario','earthquake');await page.click('#run');await page.waitForFunction(()=>window.__loadBearing.simulation?.elapsed>1);await page.click('#stop');
 await page.click('#loads-mode');assert.equal(await page.locator('#scenario').inputValue(),'occupancy');
 await page.click('#run');await page.waitForFunction(()=>window.__loadBearing.simulation?.occupancy?.count>0);
 assert.ok(Number(await page.evaluate(()=>window.__loadBearing.simulation.occupancy.tonnes))>0);
 await page.screenshot({path:'artifacts/occupancy-test.png'});await page.click('#stop');
 await page.click('#sandbox-mode');await page.click('#aim-launch');
 const target=await page.evaluate(()=>{const s=window.__loadBearing.scene;const v=s.camera.position.clone().set(0,9,0).project(s.camera);const r=s.container.getBoundingClientRect();return{x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2}});
 await page.mouse.click(target.x,target.y);
 await page.waitForFunction(()=>window.__loadBearing.simulation?.items.some(i=>i.kind==='projectile'));
 await page.waitForTimeout(1300);await page.screenshot({path:'artifacts/demolition-test.png'});
 await page.click('#stop');
 await page.click('#bridge-mode');await page.selectOption('#challenge','bridge-heavy-freight');assert.match(await page.locator('#description').textContent(),/20-tonne/);
 await page.click('#run');assert.equal(await page.evaluate(()=>window.__loadBearing.simulation.rules.vehicleMass),20000);await page.click('#stop');
 await page.setViewportSize({width:1024,height:768});await page.screenshot({path:'artifacts/workshop-1024.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: editor placement, levels, undo, persistent saves, help, scenarios, simulation controls, occupancy loads, aimed demolition projectile, heavy-freight rules, no page errors.');
} finally {await browser.close();}
