import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:412,height:915},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{await p.addInitScript(()=>{localStorage.setItem('loadbearing.demo-seen','1');localStorage.setItem('loadbearing.last-mode',JSON.stringify({challengeId:'sandbox-demolition-yard'}));});await p.goto(process.env.TEST_URL||'http://localhost:5174');await p.locator('#boot-screen').waitFor({state:'detached',timeout:60000});
await p.evaluate(()=>{document.querySelector('#showcase').value='maison-azur';document.querySelector('#load-showcase').click();document.querySelector('#walk-mode').click();});await p.waitForFunction(()=>window.__loadBearing.simulation?.walker,{},{timeout:60000});await p.waitForTimeout(500);
const start=await p.evaluate(()=>window.__loadBearing.simulation.walker.position);
const stick=p.locator('[title="Drag to move"]'),box=await stick.boundingBox(),cdp=await p.context().newCDPSession(p);const x=box.x+box.width/2,y=box.y+box.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-36}]});await p.waitForTimeout(1000);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
const end=await p.evaluate(()=>window.__loadBearing.simulation.walker.position);console.log({start,end,errors});assert.ok(Math.hypot(end[0]-start[0],end[2]-start[2])>1,'mobile stick moves walker');
await p.locator('#viewport canvas').dispatchEvent('pointerdown',{pointerId:6,pointerType:'touch',clientX:280,clientY:350});await p.locator('#viewport canvas').dispatchEvent('pointerup',{pointerId:6,pointerType:'touch',clientX:280,clientY:350});assert.equal(await p.evaluate(()=>window.__loadBearing.simulation.projectiles),0,'walking touch does not shoot');
await p.screenshot({path:'artifacts/walker-mobile.png'});await p.locator('#leave-walk').click();assert.equal(await p.evaluate(()=>window.__loadBearing.walkerMode.active),false);assert.deepEqual(errors,[]);console.log('PASS mobile stick, walk/tap separation, exit');}finally{await b.close()}
