import {Renderer} from './render.mjs';
const $=id=>document.getElementById(id),error=message=>{$('error').textContent=message;$('error').style.display='block';$('status').textContent='Fehler — siehe Anzeige.';};
try{
 const renderer=new Renderer($('view')),worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});let lastState=null,benchmark=null;
 window.__engineLab={worker,renderer,get state(){return lastState;},get benchmark(){return benchmark;}};
 const send=(type,data={})=>worker.postMessage({type,...data}),options=()=>({floors:+$('floors').value,strength:+$('strength').value});
 const reset=()=>{const o=options();send('reset',{options:o});renderer.resetCamera(o.floors*3);$('status').textContent='Neuer Turm. Keine Vorschäden.';};
 for(const [id,format] of [['strength',n=>n.toFixed(2)+'×'],['mass',n=>n+' t'],['speed',n=>n+' m/s'],['height',n=>n+' %']])$(id).addEventListener('input',()=>$(id+'-value').textContent=format(+$(id).value));
 $('reset').onclick=reset;$('floors').onchange=reset;$('pause').onclick=()=>send('pause');$('heat').onclick=()=>{renderer.heat=!renderer.heat;$('heat').textContent='Lastfarben: '+(renderer.heat?'AN':'AUS');};$('camera').onclick=()=>renderer.resetCamera(+$('floors').value*3);
 const shot=side=>({height:+$('height').value/100,mass:+$('mass').value*1000,speed:+$('speed').value,radius:1.6,side});$('fire').onclick=()=>send('fire',{shot:shot(0)});$('side').onclick=()=>send('fire',{shot:shot(1)});
 for(const [id,mass] of [['heavy',400000],['light',12000]])$(id).onclick=()=>{$('floors').value='24';$('strength').value='1';$('strength-value').textContent='1.00×';reset();send('fire',{shot:{height:.93,mass,speed:85,radius:1.6}});$('status').textContent=id==='heavy'?'Schwerer Treffer: Basislast und Verzögerung beobachten.':'Leichter Treffer: Ausschwingen beobachten.';};
 $('bench').onclick=()=>{$('bench').disabled=true;$('bench').textContent='Benchmark läuft …';send('bench');};
 worker.onerror=e=>error(e.message||'Der Physik-Worker konnte nicht geladen werden. Bitte die Seite über HTTPS öffnen und neu laden.');worker.onmessage=e=>{const m=e.data;if(m.type==='error'){error(m.message);$('bench').disabled=false;return;}if(m.type==='benchmark'){benchmark=m.result;const r=m.result;$('bench').disabled=false;$('bench').textContent='15 s / 5 Schüsse messen';const box=$('benchmark');box.style.display='block';box.replaceChildren();const text=document.createElement('div');text.textContent=`${r.meanMs.toFixed(3)} ms Mittel · ${r.p95Ms.toFixed(3)} ms p95 · ${r.physicsRealtimeFactor.toFixed(1)}× Physikdurchsatz`;box.append(text);const note=document.createElement('p');note.className='help';note.textContent=`${r.logicalInitialParts.toLocaleString('de-DE')} logische Bauteile. ${r.finalRigids} freie Körper am Ende. 1.800 feste Schritte.`;box.append(note);const a=document.createElement('a');a.textContent='Messdaten als JSON';a.download='loadbearing-custom-benchmark.json';a.href=URL.createObjectURL(new Blob([JSON.stringify({...r,userAgent:navigator.userAgent},null,2)],{type:'application/json'}));box.append(a);return;}if(m.type!=='snapshot')return;lastState=m;renderer.setState(m);const s=m.stats;$('physics').textContent=s.meanMs.toFixed(2)+' ms';$('rate').textContent=s.rate.toFixed(2)+'×';$('base').textContent=s.attached?(s.baseStress*100).toFixed(0)+' %':'Basis gebrochen';$('base-peak').textContent=(s.basePeak*100).toFixed(0)+' %';$('moment').textContent=(s.baseMoment/1e6).toFixed(1)+' MNm';$('nodes').textContent=s.nodes+' / '+s.floors;$('bodies').textContent=s.rigids+' ('+s.active+' aktiv)';$('p95').textContent=s.p95Ms.toFixed(3)+' ms';$('time').textContent=s.time.toFixed(2)+' s';$('pause').textContent=s.paused?'Weiter':'Pause';$('bar').style.width=Math.min(100,s.baseStress*66.7)+'%';$('bar').style.background=s.baseStress>1?'#f29b71':'#a9e4b5';$('scene-label').textContent=`${s.floors} Geschosse · ${(s.floors*48).toLocaleString('de-DE')} Bauteile · ${s.floors*3} Meter`;const log=$('events');log.replaceChildren();for(const ev of s.events.slice(-8).reverse()){const row=document.createElement('div');row.className=ev.type;const desc=ev.type==='shot'?`Schuss · ${ev.mass/1000} t / ${ev.speed} m/s`:ev.type==='impact'?`Einschlag · Geschoss ${ev.floor}`:ev.type==='failure'?`VERSAGEN · Geschoss ${ev.floor}`:ev.type==='ground-fracture'?`Aufschlag · ${ev.sections} freie Geschosse`:ev.type;row.textContent=`${ev.time.toFixed(2)} s  ${desc}`;log.append(row);}if(!s.events.length)log.textContent='Noch kein Einschlag.';if(s.broken.length)$('status').textContent=`Strukturversagen in Geschoss ${s.broken.join(', ')}.`;else if(s.time<.1&&!s.events.length)$('status').textContent='Bereit. Wähle einen Test.';send('consumed');};
 let frame=0,last=performance.now();function animate(now){try{renderer.render(now);}catch(e){error(e.message);return;}frame++;if(now-last>750){$('fps').textContent=Math.round(frame*1000/(now-last));frame=0;last=now;}requestAnimationFrame(animate);}requestAnimationFrame(animate);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&lastState&&!lastState.stats.paused)send('pause');});window.addEventListener('beforeunload',()=>worker.terminate());
}catch(e){error(e.stack||String(e));}
