// LOAD BEARING Engine Lab v0.1. No third-party physics dependency.
// Reduced two-plane beam dynamics + axial/torsional dynamics; free compound rigid bodies.
// SI units. This is a game model, not a structural safety tool.
export const VERSION='0.1.0';
export const DT=1/120;
const add=(a,b)=>a.map((v,i)=>v+b[i]), sub=(a,b)=>a.map((v,i)=>v-b[i]);
const mul=(a,k)=>a.map(v=>v*k), dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const norm=a=>Math.hypot(...a), unit=a=>mul(a,1/(norm(a)||1));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const qi=q=>[-q[0],-q[1],-q[2],q[3]];
const qm=(a,b)=>[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];
const qr=(q,v)=>{const t=mul(cross(q,v),2);return add(v,add(mul(t,q[3]),cross(q,t)));};
const qrot=w=>{const angle=norm(w);return angle<1e-12?[0,0,0,1]:[...mul(w,Math.sin(angle/2)/angle),Math.cos(angle/2)];};
const mmv=(a,v)=>[dot(a.slice(0,3),v),dot(a.slice(3,6),v),dot(a.slice(6,9),v)];
const inv3=a=>{const [A,B,C,D,E,F,G,H,I]=a,c=[E*I-F*H,C*H-B*I,B*F-C*E,F*G-D*I,A*I-C*G,C*D-A*F,D*H-E*G,B*G-A*H,A*E-B*D],det=A*c[0]+B*c[3]+C*c[6];if(!(Math.abs(det)>1e-15))throw Error('Singular inertia');return c.map(v=>v/det);};
const axes=q=>[[1,0,0],[0,1,0],[0,0,1]].map(v=>qr(q,v));
function inertia(m,s,q=[0,0,0,1]){const d=[m*(s[1]**2+s[2]**2)/12,m*(s[0]**2+s[2]**2)/12,m*(s[0]**2+s[1]**2)/12],a=axes(q);return Array.from({length:9},(_,k)=>a.reduce((sum,v,i)=>sum+d[i]*v[Math.floor(k/3)]*v[k%3],0));}
function outerInertia(m,r){return Array.from({length:9},(_,k)=>m*((Math.floor(k/3)===k%3?dot(r,r):0)-r[Math.floor(k/3)]*r[k%3]));}

// Symmetric lower-band storage. Beam half-bandwidth is three, so factor/solve are O(n).
export class BandMatrix {
 constructor(n,bw=3){this.n=n;this.bw=bw;this.a=new Float64Array(n*(bw+1));}
 get(i,j){if(i<j)[i,j]=[j,i];return i-j>this.bw?0:this.a[i*(this.bw+1)+i-j];}
 add(i,j,v){if(i<0||j<0)return;if(i<j)[i,j]=[j,i];if(i-j>this.bw){if(Math.abs(v)>1e-10)throw Error('Outside band');return;}this.a[i*(this.bw+1)+i-j]+=v;}
 times(x,out=new Float64Array(this.n)){out.fill(0);for(let i=0;i<this.n;i++)for(let j=Math.max(0,i-this.bw);j<=i;j++){const a=this.get(i,j);out[i]+=a*x[j];if(i!==j)out[j]+=a*x[i];}return out;}
 factor(){const n=this.n,w=this.bw,L=new Float64Array(this.a.length),get=(i,j)=>i<j||i-j>w?0:L[i*(w+1)+i-j];for(let i=0;i<n;i++)for(let j=Math.max(0,i-w);j<=i;j++){let s=this.get(i,j);for(let k=Math.max(0,i-w,j-w);k<j;k++)s-=get(i,k)*get(j,k);if(i===j){if(!(s>0))throw Error('Non-positive system matrix');L[i*(w+1)]=Math.sqrt(s);}else L[i*(w+1)+i-j]=s/get(j,j);}return rhs=>{const x=Float64Array.from(rhs);for(let i=0;i<n;i++){for(let k=Math.max(0,i-w);k<i;k++)x[i]-=get(i,k)*x[k];x[i]/=get(i,i);}for(let i=n-1;i>=0;i--){for(let k=i+1;k<=Math.min(n-1,i+w);k++)x[i]-=get(k,i)*x[k];x[i]/=get(i,i);}return x;};}
}
export function beamElement(EI,L){const a=12*EI/L**3,b=6*EI/L**2,c=4*EI/L,d=2*EI/L;return [[a,b,-a,b],[b,c,-b,d],[-a,-b,a,-b],[b,d,-b,c]];}
class ImplicitSystem {
 constructor(K,M,dt=DT){this.K=K;this.M=M;this.dt=dt;this.temp=new Float64Array(M.length);this.rhs=new Float64Array(M.length);const A=new BandMatrix(K.n,K.bw);for(let i=0;i<K.n;i++)for(let j=Math.max(0,i-K.bw);j<=i;j++)A.add(i,j,(dt*dt+dt*.008)*K.get(i,j)+(i===j?M[i]*(1+dt*.13):0));this.solve=A.factor();}
 step(u,v,force){const ku=this.K.times(u,this.temp),rhs=this.rhs;for(let i=0;i<rhs.length;i++)rhs[i]=this.M[i]*v[i]-this.dt*ku[i]+this.dt*(force?.[i]??0);const next=this.solve(rhs);for(let i=0;i<rhs.length;i++){v[i]=next[i];u[i]+=this.dt*v[i];}}
}
export function towerPieces(floors=24,width=12,storey=3){const pieces=[];let id=0;const put=(floor,kind,p,s)=>pieces.push({id:id++,floor,kind,p,s,m:s[0]*s[1]*s[2]*(kind==='glass'?2500:2400),dead:false});const cell=width/4;
 for(let f=0;f<floors;f++){for(let x=0;x<4;x++)for(let z=0;z<4;z++)put(f,'slab',[(x-1.5)*cell,0,(z-1.5)*cell],[cell-.04,.32,cell-.04]);for(let x=0;x<=4;x++)for(let z=0;z<=4;z++)if(x===0||x===4||z===0||z===4)put(f,'column',[(x-2)*cell,-storey/2,(z-2)*cell],[.48,storey-.32,.48]);for(let side of [-1,1])for(let i=0;i<4;i++){put(f,'glass',[(i-1.5)*cell,-storey/2,side*width/2],[cell-.55,storey-.68,.09]);put(f,'glass',[side*width/2,-storey/2,(i-1.5)*cell],[.09,storey-.68,cell-.55]);}}
 return pieces;
}

// Compound free rigid body. Full inertia tensor; angular momentum, not angular speed,
// is integrated in world space. Splitting transfers v + omega cross r to each child.
export class RigidBody {
 constructor(states){this.parts=[];this.m=states.reduce((s,a)=>s+a.part.m,0);this.invM=1/this.m;this.p=[0,0,0];this.v=[0,0,0];for(const s of states){this.p=add(this.p,mul(s.p,s.part.m/this.m));this.v=add(this.v,mul(s.v,s.part.m/this.m));}this.q=[...states[0].q];this.L=[0,0,0];this.I=Array(9).fill(0);this.lo=[Infinity,Infinity,Infinity];this.hi=[-Infinity,-Infinity,-Infinity];
 for(const s of states){const rw=sub(s.p,this.p),r=qr(qi(this.q),rw),localQ=qm(qi(this.q),s.q),ii=inertia(s.part.m,s.part.s,localQ),off=outerInertia(s.part.m,r);this.I=this.I.map((v,i)=>v+ii[i]+off[i]);this.L=add(this.L,add(mmv(inertia(s.part.m,s.part.s,s.q),s.w),mul(cross(rw,sub(s.v,this.v)),s.part.m)));this.parts.push({part:s.part,p:r,q:localQ});const a=axes(localQ),extent=[0,1,2].map(i=>a.reduce((v,x,j)=>v+Math.abs(x[i])*s.part.s[j]/2,0));for(let i=0;i<3;i++){this.lo[i]=Math.min(this.lo[i],r[i]-extent[i]);this.hi[i]=Math.max(this.hi[i],r[i]+extent[i]);}}
 this.invI=inv3(this.I);this.half=this.hi.map((v,i)=>(v-this.lo[i])/2);this.localCenter=this.hi.map((v,i)=>(v+this.lo[i])/2);this.sleep=0;this.asleep=false;this.contact=false;this.age=0;this.isShard=states.length===1;this.floors=new Set(states.map(s=>s.part.floor)).size;this.proxies=[];const groups=new Map();for(const p of this.parts){if(!groups.has(p.part.floor))groups.set(p.part.floor,[]);groups.get(p.part.floor).push(p);}for(const group of groups.values()){const q=group[0].q,inv=qi(q),lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const p of group){const c=qr(inv,p.p),ax=axes(qm(inv,p.q)),ex=[0,1,2].map(i=>ax.reduce((v,a,j)=>v+Math.abs(a[i])*p.part.s[j]/2,0));for(let i=0;i<3;i++){lo[i]=Math.min(lo[i],c[i]-ex[i]);hi[i]=Math.max(hi[i],c[i]+ex[i]);}}this.proxies.push({q,c:qr(q,hi.map((v,i)=>(v+lo[i])/2)),h:hi.map((v,i)=>(v-lo[i])/2)});}
 }
 invInertia(v){return qr(this.q,mmv(this.invI,qr(qi(this.q),v)));}
 omega(){return this.invInertia(this.L);}
 velocity(p){return add(this.v,cross(this.omega(),sub(p,this.p)));}
 impulse(j,p){this.v=add(this.v,mul(j,this.invM));this.L=add(this.L,cross(sub(p,this.p),j));if(this.asleep)this.sleep=0;this.asleep=false;}
 integrate(dt){this.age+=dt;this.contact=false;if(this.asleep)return;this.v[1]-=9.81*dt;this.p=add(this.p,mul(this.v,dt));const q=qm(qrot(mul(this.omega(),dt)),this.q),n=Math.hypot(...q);this.q=q.map(v=>v/n);}
 states(){const w=this.omega();return this.parts.map(s=>{const p=add(this.p,qr(this.q,s.p));return {part:s.part,p,q:qm(this.q,s.q),v:this.velocity(p),w};});}
 groundVertices(){const bounds=this.box();if(bounds.c[1]-bounds.a.reduce((v,a,i)=>v+Math.abs(a[1])*bounds.h[i],0)>.02)return [];const candidates=[];for(const proxy of this.proxies){const c=add(this.p,qr(this.q,proxy.c)),a=axes(qm(this.q,proxy.q)),h=proxy.h;if(c[1]-a.reduce((v,axis,i)=>v+Math.abs(axis[1])*h[i],0)>.02)continue;for(const p of vertices({c,a,h}))if(p[1]<.02)candidates.push(p);}candidates.sort((a,b)=>a[1]-b[1]);return candidates.slice(0,8);}
 box(){const a=axes(this.q),c=add(this.p,qr(this.q,this.localCenter));return {c,a,h:this.half};}
}
function vertices(b){const r=[];for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])r.push(add(b.c,add(mul(b.a[0],x*b.h[0]),add(mul(b.a[1],y*b.h[1]),mul(b.a[2],z*b.h[2])))));return r;}
function support(b,n){let p=b.c;for(let i=0;i<3;i++){const d=dot(b.a[i],n);if(Math.abs(d)>1e-5)p=add(p,mul(b.a[i],Math.sign(d)*b.h[i]));}return p;}
function overlap(a,b){let depth=Infinity,normal;const d=sub(a.c,b.c);for(const candidate of [...a.a,...b.a,...a.a.flatMap(x=>b.a.map(y=>cross(x,y)))]){const len=norm(candidate);if(len<1e-7)continue;const n=mul(candidate,1/len),ra=a.a.reduce((s,v,i)=>s+Math.abs(dot(n,v))*a.h[i],0),rb=b.a.reduce((s,v,i)=>s+Math.abs(dot(n,v))*b.h[i],0),p=ra+rb-Math.abs(dot(n,d));if(p<-.002)return null;if(p<depth){depth=p;normal=mul(n,dot(n,d)>=0?1:-1);}}return {n:normal,depth,p:mul(add(support(a,mul(normal,-1)),support(b,normal)),.5)};}
function effective(body,p,n){if(!body)return 0;const r=sub(p,body.p);return body.invM+dot(n,cross(body.invInertia(cross(r,n)),r));}
function contactImpulse(a,b,p,n,depth,dt){const va=a.velocity(p),vb=b?b.velocity(p):[0,0,0],rv=sub(va,vb),vn=dot(rv,n),den=effective(a,p,n)+effective(b,p,n);if(den<=0)return;const target=Math.min(1.2,.12*Math.max(0,depth-.006)/dt),j=Math.max(0,(target-vn-(vn< -3?.08*vn:0))/den);if(!j)return;a.impulse(mul(n,j),p);b?.impulse(mul(n,-j),p);const t=sub(rv,mul(n,vn)),len=norm(t);if(len>1e-7){const dir=mul(t,1/len),jt=Math.min(.55*j,len/(effective(a,p,dir)+effective(b,p,dir)));a.impulse(mul(dir,-jt),p);b?.impulse(mul(dir,jt),p);}}
function segmentBox(from,to,half,r){let lo=0,hi=1,axis=0,sign=1;for(let i=0;i<3;i++){const d=to[i]-from[i],bound=half[i]+r;if(Math.abs(d)<1e-12){if(Math.abs(from[i])>bound)return null;continue;}let a=(-bound-from[i])/d,b=(bound-from[i])/d,s=-1;if(a>b){[a,b]=[b,a];s=1;}if(a>lo){lo=a;axis=i;sign=s;}hi=Math.min(hi,b);if(lo>hi)return null;}if(lo<0||lo>1)return null;const n=[0,0,0];n[axis]=sign;return {t:lo,n};}

export class Engine {
 constructor(options={}){this.options={floors:24,strength:1,pDelta:true,fracture:true,...options};const n=Number(this.options.floors);if(!Number.isInteger(n)||n<4||n>48)throw Error('Floors must be 4..48');if(!Number.isFinite(this.options.strength)||this.options.strength<=0)throw Error('Strength must be positive');this.n=n;this.attached=n;this.h=3;this.width=12;this.time=0;this.pieces=towerPieces(n);this.byFloor=Array.from({length:n},(_,i)=>this.pieces.filter(p=>p.floor===i));this.mass=this.byFloor.map(a=>a.reduce((s,p)=>s+p.m,0));this.initialMass=[...this.mass];this.damage=new Float64Array(n);this.stress=new Float64Array(n);this.moments=new Float64Array(n);this.axialForces=new Float64Array(n);this.broken=[];this.events=[];this.rigids=[];this.shots=[];this.removed=0;this.nextShot=1;this.topPeak=0;this.basePeak=0;this.baseMomentPeak=0;this.cacheVersion=0;this.structuralColumns=Array(n).fill(16);this.u=[new Float64Array(2*n),new Float64Array(2*n)];this.v=[new Float64Array(2*n),new Float64Array(2*n)];this.uy=new Float64Array(n);this.vy=new Float64Array(n);this.twist=new Float64Array(n);this.vtwist=new Float64Array(n);this.rebuild();if(n){const g=Float64Array.from(this.mass,m=>-m*9.81);this.uy.set(this.sy.K.factor()(g));}}
 log(type,floor,extra={}){const e={time:+this.time.toFixed(3),type,floor:floor+1,...extra};this.events.push(e);if(this.events.length>64)this.events.shift();}
 rebuild(){const n=this.attached;if(!n)return;const K=new BandMatrix(n*2),Ky=new BandMatrix(n,1),Kt=new BandMatrix(n,1);this.elements=[];let weight=0;const P=new Float64Array(n);for(let i=n-1;i>=0;i--){weight+=this.mass[i]*9.81;P[i]=weight;}const M=new Float64Array(n*2),My=Float64Array.from(this.mass.slice(0,n)),Mt=new Float64Array(n);this.EA=[];this.GJ=[];
 for(let i=0;i<n;i++){const damage=Math.floor(this.damage[i]*10)/10,columns=Math.max(.04,this.structuralColumns[i]/16),factor=Math.max(.008,(1-damage)**2*columns),EI=1.8e11*factor,ke=beamElement(EI,this.h),ids=[2*i-2,2*i-1,2*i,2*i+1];this.elements.push(ke);const L=this.h,geo=[[36,3*L,-36,3*L],[3*L,4*L*L,-3*L,-L*L],[-36,-3*L,36,-3*L],[3*L,-L*L,-3*L,4*L*L]];
 for(let a=0;a<4;a++)for(let b=0;b<=a;b++)K.add(ids[a],ids[b],ke[a][b]-(this.options.pDelta?P[i]/(30*L)*geo[a][b]:0));const axial=6e9*factor/L,torsion=4e10*factor/L;this.EA[i]=axial;this.GJ[i]=torsion;for(const [mat,k] of [[Ky,axial],[Kt,torsion]]){mat.add(i,i,k);if(i){mat.add(i-1,i-1,k);mat.add(i,i-1,-k);}}M[2*i]=this.mass[i];M[2*i+1]=this.mass[i]*this.width*this.width/12;Mt[i]=this.mass[i]*this.width*this.width/6;}
 this.sx=new ImplicitSystem(K,M);this.sz=new ImplicitSystem(K,M);this.sy=new ImplicitSystem(Ky,My);this.st=new ImplicitSystem(Kt,Mt);this.gravity=Float64Array.from(My,m=>-m*9.81);this.cacheVersion++;
 }
 floorPose(i){return {p:[this.u[0][2*i],(i+1)*this.h+this.uy[i],this.u[1][2*i]],q:qrot([this.u[1][2*i+1],this.twist[i],-this.u[0][2*i+1]]),v:[this.v[0][2*i],this.vy[i],this.v[1][2*i]],w:[this.v[1][2*i+1],this.vtwist[i],-this.v[0][2*i+1]]};}
 pieceState(part){const f=this.floorPose(part.floor),r=qr(f.q,part.p),p=add(f.p,r);return {part,p,q:f.q,v:add(f.v,cross(f.w,r)),w:f.w};}
 applyImpulse(floor,impulse,point){if(floor<0||floor>=this.attached)return false;const f=this.floorPose(floor),torque=cross(sub(point,f.p),impulse),m=this.mass[floor],I=m*this.width*this.width/12;this.v[0][2*floor]+=impulse[0]/m;this.v[1][2*floor]+=impulse[2]/m;this.v[0][2*floor+1]-=torque[2]/I;this.v[1][2*floor+1]+=torque[0]/I;this.vy[floor]+=impulse[1]/m;this.vtwist[floor]+=torque[1]/(2*I);return true;}
 fire({height=.93,mass=150000,speed=85,radius=1.6,side=0}={}){if(![height,mass,speed,radius,side].every(Number.isFinite)||mass<=0||speed<=0||radius<=0)throw Error('Invalid projectile');height=clamp(height,.02,1);const angle=side*Math.PI/2,dir=[Math.cos(angle),0,Math.sin(angle)],target=[0,this.n*this.h*height,0],p=sub(target,mul(dir,34));p[1]+=.5*9.81*(28/speed)**2;const shot={id:this.nextShot++,p,v:mul(dir,speed),mass,radius,age:0,hit:false};this.shots.push(shot);if(this.shots.length>24)this.shots.shift();this.log('shot',Math.floor(height*this.n),{mass,speed});return shot;}
 damagePiece(part,energy){if(part.dead||energy<(part.kind==='glass'?16000:2.4e6))return;const state=this.pieceState(part);part.dead=true;this.removed++;this.mass[part.floor]-=part.m;if(part.kind==='column')this.structuralColumns[part.floor]--;if(this.rigids.length<180){const shard={...part,id:this.pieces.length,dead:false};this.pieces.push(shard);state.part=shard;this.rigids.push(new RigidBody([state]));}else{part.dead=false;this.removed--;this.mass[part.floor]+=part.m;if(part.kind==='column')this.structuralColumns[part.floor]++;return;}this.rebuild();}
 projectileStep(dt){for(const s of this.shots){s.age+=dt;if(s.hit){s.v[1]-=9.81*dt;s.p=add(s.p,mul(s.v,dt));if(s.p[1]<s.radius){s.p[1]=s.radius;s.v[1]=Math.abs(s.v[1])*.15;s.v[0]*=.94;s.v[2]*=.94;}continue;}const from=s.p;s.v[1]-=9.81*dt;const to=add(from,mul(s.v,dt));let first=null;
 for(let i=0;i<this.attached;i++){const f=this.floorPose(i);if(Math.min(from[1],to[1])-s.radius>f.p[1]+1||Math.max(from[1],to[1])+s.radius<f.p[1]-this.h-1)continue;const inv=qi(f.q),a=qr(inv,sub(from,f.p)),b=qr(inv,sub(to,f.p));for(const part of this.byFloor[i]){if(part.dead)continue;const hit=segmentBox(sub(a,part.p),sub(b,part.p),mul(part.s,.5),s.radius);if(hit&&(!first||hit.t<first.t))first={...hit,n:qr(f.q,hit.n),part,floor:i};}}
 for(const body of this.rigids){const box=body.box(),inv=qi(body.q),a=qr(inv,sub(from,box.c)),b=qr(inv,sub(to,box.c)),hit=segmentBox(a,b,box.h,s.radius);if(hit&&(!first||hit.t<first.t))first={...hit,n:qr(body.q,hit.n),body};}
 if(!first){s.p=to;if(s.p[1]<=s.radius){s.hit=true;s.p[1]=s.radius;s.v[1]=Math.abs(s.v[1])*.1;}continue;}s.p=add(from,mul(sub(to,from),first.t));const point=sub(s.p,mul(first.n,s.radius)),body=first.body,floor=first.floor;const f=body?null:this.floorPose(floor),r=f?sub(point,f.p):[0,0,0],velocity=body?body.velocity(point):add(f.v,cross(f.w,r)),m=body?body.m:this.mass[floor],rxn=cross(r,first.n),I=m*this.width*this.width/12,invEffective=body?effective(body,point,first.n):1/m+(rxn[0]**2+rxn[2]**2+rxn[1]**2/2)/I;const vn=dot(sub(s.v,velocity),first.n),j=vn<0?-(1.1)*vn/(1/s.mass+invEffective):0,impulse=mul(first.n,-j);s.v=add(s.v,mul(first.n,j/s.mass));s.hit=true;if(body)body.impulse(impulse,point);else{this.applyImpulse(floor,impulse,point);const energy=.5*j*j/s.mass;const hitPart=first.part;this.damagePiece(hitPart,energy);this.log('impact',floor,{impulse:+j.toFixed(0),part:hitPart.kind});}}
 this.shots=this.shots.filter(s=>s.age<25);
 }
 detach(floor,reason='overload'){if(floor<0||floor>=this.attached)return;const old=this.attached,states=[];for(let i=floor;i<old;i++)for(const p of this.byFloor[i])if(!p.dead)states.push(this.pieceState(p));if(states.length)this.rigids.push(new RigidBody(states));this.broken.push(floor);this.log('failure',floor,{reason,utilization:+this.stress[floor].toFixed(3)});this.attached=floor;this.rebuild();}
 structuralStep(){const n=this.attached;if(!n)return;this.sx.step(this.u[0].subarray(0,2*n),this.v[0].subarray(0,2*n));this.sz.step(this.u[1].subarray(0,2*n),this.v[1].subarray(0,2*n));this.sy.step(this.uy.subarray(0,n),this.vy.subarray(0,n),this.gravity);this.st.step(this.twist.subarray(0,n),this.vtwist.subarray(0,n));let refactor=false,failed=-1;
 for(let i=0;i<n;i++){const ke=this.elements[i],forces=this.u.map(u=>{const local=[i?u[2*i-2]:0,i?u[2*i-1]:0,u[2*i],u[2*i+1]];return ke.map(row=>dot(row,local));});const moment=Math.max(Math.hypot(forces[0][1],forces[1][1]),Math.hypot(forces[0][3],forces[1][3])),shear=Math.hypot(forces[0][0],forces[1][0]),axial=Math.abs(this.EA[i]*(this.uy[i]-(i?this.uy[i-1]:0))),torsion=Math.abs(this.GJ[i]*(this.twist[i]-(i?this.twist[i-1]:0))),remaining=Math.max(.04,this.structuralColumns[i]/16)*(1-.6*this.damage[i]),strength=this.options.strength*remaining;
 this.moments[i]=moment;this.axialForces[i]=axial;const ratio=Math.max(moment/(2.8e8*strength)+axial/(2e8*strength)*.3,shear/(3e7*strength),axial/(2e8*strength),torsion/(1.2e8*strength));this.stress[i]=ratio;if(i===0){this.basePeak=Math.max(this.basePeak,ratio);this.baseMomentPeak=Math.max(this.baseMomentPeak,moment);}if(this.options.fracture&&ratio>1){const old=Math.floor(this.damage[i]*10);this.damage[i]=Math.min(1,this.damage[i]+DT*Math.min(8,(ratio-1)**2)*.6);if(Math.floor(this.damage[i]*10)!==old)refactor=true;if(this.damage[i]>=.95||this.structuralColumns[i]===0){if(failed<0)failed=i;}}
 }
 this.topPeak=Math.max(this.topPeak,Math.hypot(this.u[0][2*(n-1)],this.u[1][2*(n-1)]));if(failed>=0)this.detach(failed);else if(refactor)this.rebuild();
 }
 split(body){const groups=new Map();for(const s of body.states()){const k=s.part.floor;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(s);}if(groups.size<2||this.rigids.length+groups.size>180)return;const idx=this.rigids.indexOf(body);this.rigids.splice(idx,1,...[...groups.values()].map(states=>new RigidBody(states)));this.log('ground-fracture',0,{sections:groups.size});}
 rigidStep(dt){const split=new Set();for(const b of this.rigids)b.integrate(dt);const ground=[];for(const b of this.rigids){if(b.asleep)continue;const corners=b.groundVertices();for(const p of corners)if(p[1]<.015){ground.push({b,p,depth:Math.max(0,-p[1])});b.contact=true;if(b.floors>1&&b.velocity(p)[1]<-9&&b.age>.25)split.add(b);}}
 const broad=this.rigids.map(b=>{const box=b.box(),e=[0,1,2].map(i=>box.a.reduce((s,v,j)=>s+Math.abs(v[i])*box.h[j],0));return {b,box,min:sub(box.c,e),max:add(box.c,e)};}).sort((a,b)=>a.min[0]-b.min[0]);const contacts=[];
 for(let i=0;i<broad.length;i++)for(let j=i+1;j<broad.length&&broad[j].min[0]<=broad[i].max[0];j++){const a=broad[i],b=broad[j];if(a.b.asleep&&b.b.asleep||a.min[1]>b.max[1]||b.min[1]>a.max[1]||a.min[2]>b.max[2]||b.min[2]>a.max[2])continue;const c=overlap(a.box,b.box);if(c){contacts.push({a:a.b,b:b.b,...c});a.b.contact=b.b.contact=true;}}
 // Supported storeys act as static contact hulls in this first prototype. Their
 // detailed interior is not a collision mesh; the lab intentionally has no walker.
 for(const row of broad){if(row.b.asleep)continue;for(let i=0;i<this.attached;i++){const f=this.floorPose(i);if(row.min[1]>f.p[1]+.2||row.max[1]<f.p[1]-this.h)continue;const box={c:add(f.p,qr(f.q,[0,-this.h/2,0])),a:axes(f.q),h:[this.width/2,this.h/2,this.width/2]},c=overlap(row.box,box);if(c){contacts.push({a:row.b,b:null,...c});row.b.contact=true;}}}
 for(let it=0;it<6;it++){for(const c of ground)contactImpulse(c.b,null,c.p,[0,1,0],c.depth,dt);for(const c of contacts)contactImpulse(c.a,c.b,c.p,c.n,c.depth,dt);}
 for(const b of this.rigids){if(b.asleep)continue;const minY=Math.min(...b.groundVertices().map(p=>p[1]),0);if(minY<-.01)b.p[1]-=Math.max(-.6,minY)*.5;if(b.contact&&norm(b.v)<.13&&norm(b.omega())<.04){b.sleep+=dt;if(b.sleep>1){b.asleep=true;b.v=[0,0,0];b.L=[0,0,0];}}else b.sleep=0;}
 for(const b of split)this.split(b);
 }
 step(){this.projectileStep(DT);this.structuralStep();this.rigidStep(DT);this.time+=DT;}
 snapshot(){const transforms=new Float32Array(this.pieces.length*8);const write=(id,p,q,state)=>{transforms.set([...p,...q,state],id*8);};for(let i=0;i<this.attached;i++)for(const part of this.byFloor[i])if(!part.dead){const s=this.pieceState(part);write(part.id,s.p,s.q,Math.min(1,this.stress[i]/1.5));}for(const b of this.rigids)for(const s of b.states())write(s.part.id,s.p,s.q,.8);return {transforms,pieces:this.pieces.map(p=>({id:p.id,s:p.s,kind:p.kind})),shots:this.shots.map(s=>({p:s.p,radius:s.radius})),stats:{time:this.time,floors:this.n,attached:this.attached,parts:this.pieces.filter(p=>!p.dead).length,nodes:this.attached,rigids:this.rigids.length,active:this.rigids.filter(b=>!b.asleep).length,baseStress:this.stress[0]||0,basePeak:this.basePeak,baseMoment:this.moments[0]||0,baseMomentPeak:this.baseMomentPeak,topPeak:this.topPeak,broken:this.broken.map(i=>i+1),damage:Array.from(this.damage),events:this.events}};}
}
export const math={add,sub,mul,dot,cross,norm,unit,qr,qi,qm,qrot,inertia,mmv};
