// Small WebGL2 instanced renderer. No physics or graphics dependencies.
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),unit=a=>a.map(v=>v/(Math.hypot(...a)||1));
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
function multiply(a,b){const c=new Float32Array(16);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)c[j*4+i]+=a[k*4+i]*b[j*4+k];return c;}
function view(eye,target){const z=unit(sub(eye,target)),x=unit(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function perspective(aspect){const f=1/Math.tan(48*Math.PI/360),n=.2,far=900;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function ortho(s){return new Float32Array([1/s,0,0,0,0,1/s,0,0,0,0,-2/600,0,0,0,-1,1]);}
const vertex=`#version 300 es
precision highp float;
layout(location=0) in vec3 position;
layout(location=1) in vec3 normal;
layout(location=2) in mat4 model;
layout(location=6) in vec3 color;
uniform mat4 vp;uniform mat4 lightVP;
out vec3 vNormal;out vec3 vColor;out vec3 vWorld;out vec3 vLocal;out vec4 vShadow;
void main(){vec4 w=model*vec4(position,1.0);vWorld=w.xyz;vNormal=normalize(mat3(model)*normal);vColor=color;vLocal=position;vShadow=lightVP*w;gl_Position=vp*w;}`;
const fragment=`#version 300 es
precision highp float;
in vec3 vNormal;in vec3 vColor;in vec3 vWorld;in vec3 vLocal;in vec4 vShadow;
uniform vec3 eye;uniform sampler2D shadowMap;out vec4 outputColor;
void main(){vec3 n=normalize(vNormal),l=normalize(vec3(-.45,.85,.55));float sun=max(0.0,dot(n,l));vec3 sh=vShadow.xyz/vShadow.w*.5+.5;float shadow=0.0;if(sh.x>0.0&&sh.x<1.0&&sh.y>0.0&&sh.y<1.0&&sh.z<1.0){float bias=max(.0012*(1.0-sun),.0005);for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float z=texture(shadowMap,sh.xy+vec2(x,y)/1536.0).r;shadow+=sh.z-bias>z?1.0/9.0:0.0;}}
vec3 c=vColor*(.42+.58*sun*(1.0-.68*shadow));float fog=1.0-exp(-pow(length(vWorld-eye)/390.0,2.0));c=mix(c,vec3(.075,.11,.14),fog);outputColor=vec4(pow(c,vec3(.82)),1.0);}`;
const depthFragment=`#version 300 es
precision highp float;out vec4 color;void main(){color=vec4(1);}`;
function cube(){const a=[];for(const [normal,u,v] of [[[1,0,0],[0,0,-1],[0,1,0]],[[-1,0,0],[0,0,1],[0,1,0]],[[0,1,0],[1,0,0],[0,0,-1]],[[0,-1,0],[1,0,0],[0,0,1]],[[0,0,1],[1,0,0],[0,1,0]],[[0,0,-1],[-1,0,0],[0,1,0]]]){for(const [x,y] of [[-1,-1],[1,-1],[1,1],[-1,-1],[1,1],[-1,1]])a.push(...normal.map((n,i)=>(n+x*u[i]+y*v[i])*.5),...normal);}return new Float32Array(a);}
function sphere(){const out=[],point=(i,j)=>{const t=i*Math.PI/10,p=j*2*Math.PI/16;return [Math.sin(t)*Math.cos(p),Math.cos(t),Math.sin(t)*Math.sin(p)];};for(let i=0;i<10;i++)for(let j=0;j<16;j++){const a=point(i,j),b=point(i+1,j),c=point(i+1,j+1),d=point(i,j+1);for(const p of [a,c,b,a,d,c])out.push(...p.map(v=>v*.5),...p);}return new Float32Array(out);}
export class Renderer {
 constructor(canvas){this.canvas=canvas;const gl=this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false});if(!gl)return new CanvasRenderer(canvas);const program=frag=>{const p=gl.createProgram();for(const [type,src] of [[gl.VERTEX_SHADER,vertex],[gl.FRAGMENT_SHADER,frag]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;};this.program=program(fragment);this.depth=program(depthFragment);this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,cube(),gl.STATIC_DRAW);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,24,i*12);}this.instanceBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.instanceBuffer);for(let i=0;i<4;i++){gl.enableVertexAttribArray(2+i);gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,76,i*16);gl.vertexAttribDivisor(2+i,1);}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,3,gl.FLOAT,false,76,64);gl.vertexAttribDivisor(6,1);
 this.sphereVAO=gl.createVertexArray();gl.bindVertexArray(this.sphereVAO);const sb=gl.createBuffer(),sv=sphere();this.sphereVertices=sv.length/6;gl.bindBuffer(gl.ARRAY_BUFFER,sb);gl.bufferData(gl.ARRAY_BUFFER,sv,gl.STATIC_DRAW);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,24,i*12);}gl.bindBuffer(gl.ARRAY_BUFFER,this.instanceBuffer);for(let i=2;i<=6;i++){gl.enableVertexAttribArray(i);gl.vertexAttribDivisor(i,1);}gl.bindVertexArray(this.vao);this.shadow=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadow);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,1536,1536,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);for(const [a,b] of [[gl.TEXTURE_MIN_FILTER,gl.NEAREST],[gl.TEXTURE_MAG_FILTER,gl.NEAREST],[gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE],[gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE]])gl.texParameteri(gl.TEXTURE_2D,a,b);this.fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadow,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer unavailable');gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);this.heat=false;this.resetCamera(72);this.drag=null;
 canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey};});canvas.addEventListener('pointerup',()=>this.drag=null);canvas.addEventListener('pointercancel',()=>this.drag=null);canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(this.drag.pan){this.target[0]-=dx*this.radius*.0015*Math.cos(this.yaw);this.target[2]+=dx*this.radius*.0015*Math.sin(this.yaw);this.target[1]+=dy*this.radius*.0015;}else{this.yaw-=dx*.006;this.pitch=Math.max(.04,Math.min(1.4,this.pitch+dy*.005));}this.drag.x=e.clientX;this.drag.y=e.clientY;});canvas.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(20,Math.min(500,this.radius*Math.exp(e.deltaY*.001)));},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());this.previous=null;this.current=null;this.received=0;
 }
 resetCamera(height){this.height=height;this.target=[height*.14,height*.38,0];this.radius=Math.max(90,height*2.25);this.yaw=.7;this.pitch=.28;}
 setState(state){this.previous=this.current;this.current=state;this.received=performance.now();}
 render(now){const gl=this.gl,c=this.canvas,dpr=Math.min(devicePixelRatio||1,1.7),width=Math.floor(c.clientWidth*dpr),height=Math.floor(c.clientHeight*dpr);if(!width||!height)return;if(c.width!==width||c.height!==height){c.width=width;c.height=height;}const rows=[],push=(p,q,s,color)=>{const [x,y,z,w]=q,xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;rows.push((1-2*(yy+zz))*s[0],2*(xy+wz)*s[0],2*(xz-wy)*s[0],0,2*(xy-wz)*s[1],(1-2*(xx+zz))*s[1],2*(yz+wx)*s[1],0,2*(xz+wy)*s[2],2*(yz-wx)*s[2],(1-2*(xx+yy))*s[2],0,...p,1,...color);};
 push([0,-.18,0],[0,0,0,1],[440,.25,440],[.13,.18,.20]);for(let i=-200;i<=200;i+=10){push([i,-.04,0],[0,0,0,1],[.035,.012,400],[.2,.27,.29]);push([0,-.04,i],[0,0,0,1],[400,.012,.035],[.2,.27,.29]);}push([0,-.015,0],[0,0,0,1],[15,.28,15],[.53,.56,.53]);for(let i=0;i<12;i++){push([-9+i*1.6,-.025,-9],[0,0,0,1],[.8,.03,.32],[.77,.52,.14]);push([-9+i*1.6,-.025,9],[0,0,0,1],[.8,.03,.32],[.77,.52,.14]);}
 let boxCount=rows.length/19;if(this.current){const a=this.current.transforms,b=this.previous?.transforms,t=this.current.stats.paused?1:Math.min(1,(now-this.received)/50);for(const part of this.current.pieces){const o=part.id*8;if(a[o+6]===0&&a[o+3]===0&&a[o+4]===0&&a[o+5]===0)continue;let p=Array.from(a.subarray(o,o+3)),q=Array.from(a.subarray(o+3,o+7));if(b&&o+7<b.length&&b[o+6]!==0){p=p.map((v,i)=>b[o+i]+(v-b[o+i])*t);const sign=q.reduce((s,v,i)=>s+v*b[o+3+i],0)<0?-1:1;q=q.map((v,i)=>b[o+3+i]*(1-t)+sign*v*t);const n=Math.hypot(...q);q=q.map(v=>v/n);}let color=part.kind==='glass'?[.13,.43,.48]:part.kind==='column'?[.77,.74,.65]:[.62,.68,.69];if(this.heat){const h=a[o+7];color=[.22+.75*h,.78-.62*h,.50-.35*h];}push(p,q,part.s,color);}boxCount=rows.length/19;for(const s of this.current.shots)push(s.p,[0,0,0,1],[s.radius*2,s.radius*2,s.radius*2],[.96,.30,.09]);}
 const eye=[this.target[0]+this.radius*Math.sin(this.yaw)*Math.cos(this.pitch),this.target[1]+this.radius*Math.sin(this.pitch),this.target[2]+this.radius*Math.cos(this.yaw)*Math.cos(this.pitch)],vp=multiply(perspective(width/height),view(eye,this.target));const lv=multiply(ortho(Math.max(95,this.height)),view([-130,210,130],[15,25,0]));gl.bindVertexArray(this.vao);gl.bindBuffer(gl.ARRAY_BUFFER,this.instanceBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(rows),gl.DYNAMIC_DRAW);const count=rows.length/19;const draw=()=>{gl.bindVertexArray(this.vao);gl.drawArraysInstanced(gl.TRIANGLES,0,36,boxCount);if(count>boxCount){gl.bindVertexArray(this.sphereVAO);gl.bindBuffer(gl.ARRAY_BUFFER,this.instanceBuffer);for(let i=0;i<4;i++)gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,76,boxCount*76+i*16);gl.vertexAttribPointer(6,3,gl.FLOAT,false,76,boxCount*76+64);gl.drawArraysInstanced(gl.TRIANGLES,0,this.sphereVertices,count-boxCount);}};
 gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.viewport(0,0,1536,1536);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(this.depth);gl.uniformMatrix4fv(gl.getUniformLocation(this.depth,'vp'),false,lv);gl.uniformMatrix4fv(gl.getUniformLocation(this.depth,'lightVP'),false,lv);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(2,4);draw();gl.disable(gl.POLYGON_OFFSET_FILL);
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,width,height);gl.clearColor(.075,.11,.14,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);gl.uniformMatrix4fv(gl.getUniformLocation(this.program,'vp'),false,vp);gl.uniformMatrix4fv(gl.getUniformLocation(this.program,'lightVP'),false,lv);gl.uniform3fv(gl.getUniformLocation(this.program,'eye'),eye);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.shadow);gl.uniform1i(gl.getUniformLocation(this.program,'shadowMap'),0);draw();
 }
}


// Software preview for browsers without WebGL2. Physics still runs in the same worker.
class CanvasRenderer {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');if(!this.ctx)throw Error('Kein Canvas-Kontext verfügbar');this.fallback=true;this.heat=false;this.resetCamera(72);this.current=null;this.previous=null;this.drag=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey};});for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,()=>this.drag=null);canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(this.drag.pan){this.target[0]-=dx*this.radius*.0015*Math.cos(this.yaw);this.target[2]+=dx*this.radius*.0015*Math.sin(this.yaw);this.target[1]+=dy*this.radius*.0015;}else{this.yaw-=dx*.006;this.pitch=Math.max(.04,Math.min(1.4,this.pitch+dy*.005));}this.drag.x=e.clientX;this.drag.y=e.clientY;});canvas.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(20,Math.min(500,this.radius*Math.exp(e.deltaY*.001)));},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());}
 resetCamera(h){Renderer.prototype.resetCamera.call(this,h);}
 setState(s){Renderer.prototype.setState.call(this,s);}
 render(now){const c=this.canvas,ctx=this.ctx,w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;if(c.width!==w||c.height!==h){c.width=w;c.height=h;}ctx.fillStyle='#17232b';ctx.fillRect(0,0,w,h);const eye=[this.target[0]+this.radius*Math.sin(this.yaw)*Math.cos(this.pitch),this.target[1]+this.radius*Math.sin(this.pitch),this.target[2]+this.radius*Math.cos(this.yaw)*Math.cos(this.pitch)],z=unit(sub(this.target,eye)),x=unit(cross(z,[0,1,0])),y=cross(x,z),f=h/(2*Math.tan(24*Math.PI/180));const project=p=>{const r=sub(p,eye),d=dot(r,z);return d>.1?[w/2+f*dot(r,x)/d,h/2-f*dot(r,y)/d,d]:null;},rot=(q,v)=>{const t=cross(q,v).map(n=>2*n),b=cross(q,t);return v.map((n,i)=>n+q[3]*t[i]+b[i]);};ctx.strokeStyle='#2a3b43';ctx.lineWidth=1;for(let i=-200;i<=200;i+=10)for(const a of [[[i,0,-200],[i,0,200]],[[-200,0,i],[200,0,i]]]){const p=a.map(project);if(p.every(Boolean)){ctx.beginPath();ctx.moveTo(p[0][0],p[0][1]);ctx.lineTo(p[1][0],p[1][1]);ctx.stroke();}}
 const quads=[],faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]],light=unit([-.45,.85,.55]);const box=(p,q,s,col)=>{const v=[];for(const a of [-1,1])for(const b of [-1,1])for(const d of [-1,1]){const r=rot(q,[a*s[0]/2,b*s[1]/2,d*s[2]/2]);v.push(p.map((n,i)=>n+r[i]));}for(const ids of faces){const world=ids.map(i=>v[i]),normal=unit(cross(sub(world[1],world[0]),sub(world[2],world[0])));if(dot(normal,sub(eye,world[0]))<=0)continue;const points=world.map(project);if(points.some(p=>!p))continue;const brightness=.45+.55*Math.max(0,dot(normal,light));quads.push({points,z:points.reduce((s,p)=>s+p[2]/4,0),color:'rgb('+col.map(n=>Math.round(Math.pow(n*brightness,.82)*255)).join(',')+')'});}};
 box([0,-.1,0],[0,0,0,1],[15,.3,15],[.6,.6,.55]);if(this.current){const a=this.current.transforms;for(const part of this.current.pieces){const o=part.id*8,q=Array.from(a.subarray(o+3,o+7));if(!q.some(n=>n!==0))continue;let color=part.kind==='glass'?[.13,.43,.48]:part.kind==='column'?[.77,.74,.65]:[.62,.68,.69];if(this.heat){const t=a[o+7];color=[.22+.75*t,.78-.62*t,.5-.35*t];}box(Array.from(a.subarray(o,o+3)),q,part.s,color);}}quads.sort((a,b)=>b.z-a.z);for(const q of quads){ctx.fillStyle=q.color;ctx.beginPath();ctx.moveTo(...q.points[0].slice(0,2));for(let i=1;i<4;i++)ctx.lineTo(...q.points[i].slice(0,2));ctx.closePath();ctx.fill();}if(this.current)for(const shot of this.current.shots){const p=project(shot.p);if(p){ctx.fillStyle='#f07a35';ctx.beginPath();ctx.arc(p[0],p[1],Math.max(1,shot.radius*f/p[2]),0,Math.PI*2);ctx.fill();}}ctx.fillStyle='#9caeb4';ctx.font='10px monospace';ctx.fillText('SOFTWAREVORSCHAU · WebGL2 nicht verfügbar',20,h-115);
 }
}
