import {Engine,DT,VERSION} from './engine.mjs';
let engine=new Engine(),paused=false,inFlight=false,last=performance.now(),acc=0,samples=[],startWall=performance.now(),startSim=0,lastSnapshot=0;
const stats=a=>{const s=[...a].sort((a,b)=>a-b),sum=a.reduce((a,b)=>a+b,0);return {meanMs:a.length?sum/a.length:0,p95Ms:s.length?s[Math.floor((s.length-1)*.95)]:0,maxMs:s.length?s.at(-1):0};};
function snapshot(force=false){if(inFlight&&!force)return;const state=engine.snapshot();state.stats={...state.stats,...stats(samples),version:VERSION,paused,rate:paused?0:(engine.time-startSim)/Math.max(.001,(performance.now()-startWall)/1000)};postMessage({type:'snapshot',...state},[state.transforms.buffer]);inFlight=true;}
function reset(options){engine=new Engine(options);samples=[];last=performance.now();acc=0;startWall=last;startSim=0;paused=false;inFlight=false;snapshot(true);}
function benchmark(){const options={floors:engine.n,strength:1},e=new Engine(options),times=[],stages={quiet:[],impact:[],collapse:[]};for(let i=0;i<60;i++)new Engine({floors:4,fracture:false}).step();let launchMs=0;for(let i=0;i<1800;i++){if(i===120||i===480||i===840||i===1080||i===1320){const t=performance.now();e.fire({mass:i===120?400000:180000,speed:85,height:i===120?.93:.55,side:i===480?1:0});launchMs+=performance.now()-t;}const t=performance.now();e.step();const ms=performance.now()-t;times.push(ms);stages[i<120?'quiet':e.attached===0?'collapse':'impact'].push(ms);}return {engine:VERSION,scenario:'tower-five-shot-v1',floors:e.n,logicalInitialParts:e.n*48,dt:DT,steps:1800,simulatedSeconds:15,shotTimes:[1,4,7,9,11],...stats(times),physicsWallMs:times.reduce((a,b)=>a+b,0),launchMs,physicsRealtimeFactor:DT*1000/stats(times).meanMs,stages:Object.fromEntries(Object.entries(stages).map(([k,v])=>[k,{steps:v.length,...stats(v)}])),failures:e.events.filter(e=>e.type==='failure'),finalRigids:e.rigids.length,note:'Worker physics only. Excludes rendering, snapshots and initialization. Reduced custom model; NOT an equal-quality Jolt comparison.'};}
onmessage=e=>{try{const m=e.data;if(m.type==='consumed')inFlight=false;else if(m.type==='reset')reset(m.options);else if(m.type==='fire')engine.fire(m.shot);else if(m.type==='pause'){paused=!paused;startWall=performance.now();startSim=engine.time;last=startWall;acc=0;snapshot(true);}else if(m.type==='bench'){const r=benchmark();postMessage({type:'benchmark',result:r});last=performance.now();acc=0;startWall=last;startSim=engine.time;}else if(m.type==='advance'){for(let i=0;i<Math.min(7200,Math.max(0,m.steps||0));i++)engine.step();snapshot(true);}}catch(error){paused=true;postMessage({type:'error',message:error.stack||String(error)});}};
function loop(){try{const now=performance.now(),elapsed=Math.min(.1,(now-last)/1000);last=now;if(!paused){acc=Math.min(.12,acc+elapsed);let steps=0;while(acc>=DT&&steps++<12){const t=performance.now();engine.step();samples.push(performance.now()-t);if(samples.length>480)samples.shift();acc-=DT;}}if(now-lastSnapshot>50){snapshot();lastSnapshot=now;}}catch(error){paused=true;postMessage({type:'error',message:error.stack||String(error)});}setTimeout(loop,4);}
snapshot(true);loop();
