import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8777/games/loadbearing-engine-lab/');
 await page.waitForFunction(()=>window.__engineLab?.state?.stats.time>.1,{},{timeout:60000});
 assert.equal(await page.locator('#floors').inputValue(),'24');
 assert.equal(await page.locator('#error').innerText(),'');
 await page.screenshot({path:'artifacts/initial.png'});
 await page.click('#heavy');
 await page.evaluate(()=>{window.__engineLab.worker.postMessage({type:'pause'});window.__engineLab.worker.postMessage({type:'advance',steps:720});});
 await page.waitForFunction(()=>window.__engineLab.state.stats.time>=5.99&&window.__engineLab.state.stats.events.some(e=>e.type==='shot'&&e.mass===400000),{},{timeout:120000});
 const state=await page.evaluate(()=>window.__engineLab.state.stats);
 assert.equal(state.events.find(e=>e.type==='failure').floor,1);
 assert.ok(state.events.find(e=>e.type==='impact').floor>=20);
 await page.screenshot({path:'artifacts/heavy-hit.png'});
 await page.evaluate(()=>window.__engineLab.worker.postMessage({type:'advance',steps:1800}));
 await page.waitForFunction(()=>window.__engineLab.state.stats.time>=20,{},{timeout:120000});
 await page.screenshot({path:'artifacts/collapse.png'});
 await page.click('#light');
 await page.evaluate(()=>{window.__engineLab.worker.postMessage({type:'pause'});window.__engineLab.worker.postMessage({type:'advance',steps:1800});});
 await page.waitForFunction(()=>window.__engineLab.state.stats.time>=14.99&&window.__engineLab.state.stats.events.some(e=>e.type==='shot'&&e.mass===12000),{},{timeout:120000});
 assert.deepEqual(await page.evaluate(()=>window.__engineLab.state.stats.broken),[]);
 await page.click('#bench');
 await page.waitForFunction(()=>window.__engineLab.benchmark,{},{timeout:120000});
 const benchmark=await page.evaluate(()=>window.__engineLab.benchmark);
 assert.equal(benchmark.steps,1800);assert.ok(benchmark.meanMs>0&&Number.isFinite(benchmark.meanMs));
 const backend=await page.evaluate(()=>window.__engineLab.renderer.fallback?'Canvas2D fallback':'WebGL2');
 if(backend==='WebGL2')assert.equal(await page.evaluate(()=>window.__engineLab.renderer.gl.getError()),0);
 await writeFile('artifacts/browser-result.json',JSON.stringify({backend,errors,benchmark},null,2));
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'artifacts/mobile.png'});
 assert.deepEqual(errors,[]);console.log('BROWSER_PASS '+JSON.stringify({backend,benchmark}));
}finally{await browser.close();}
