type Point = { x:number; y:number; z:number };
export type DestructionAudioStats = { played:number; active:number; dropped:number };
export class DestructionAudio {
 enabled=true; volume=.45; readonly stats:DestructionAudioStats={played:0,active:0,dropped:0};
 private context?:AudioContext; private master?:GainNode; private noise?:AudioBuffer; private voices=new Set<AudioNode>(); private lastByKind=new Map<string,number>(); private unlockBound:()=>void;
 constructor(){this.unlockBound=()=>{void this.unlock();};window.addEventListener('pointerdown',this.unlockBound,{passive:true,capture:true});window.addEventListener('keydown',this.unlockBound,{passive:true,capture:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)this.suspend();else if(this.context?.state==='suspended')void this.context.resume().catch(()=>undefined);});}
 private async unlock(){if(!this.enabled)return;if(this.context){if(this.context.state==='suspended')await this.context.resume().catch(()=>undefined);return;}const C=window.AudioContext;if(!C)return;try{this.context=new C();this.master=this.context.createGain();this.master.gain.value=this.volume;this.master.connect(this.context.destination);const rate=this.context.sampleRate,buffer=this.context.createBuffer(1,Math.ceil(rate*.5),rate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,1.8);this.noise=buffer;await this.context.resume();}catch{this.context=undefined;this.master=undefined;this.noise=undefined;}}
 emit(kind:string,position:Point,camera:any,strength=1){
  if(!this.enabled||document.hidden||!this.context||this.context.state!=='running'||!this.master||!this.noise){this.stats.dropped++;return;}
  const now=performance.now(),last=this.lastByKind.get(kind)??-Infinity;if(now-last<90){this.stats.dropped++;return;}this.lastByKind.set(kind,now);if(this.voices.size+2>8){this.stats.dropped++;return;}
  const cp=camera?.position,dx=(cp?.x??0)-position.x,dy=(cp?.y??0)-position.y,dz=(cp?.z??0)-position.z,d=Math.hypot(dx,dy,dz),atten=1/(1+d*d/1600);if(atten<.015){this.stats.dropped++;return;}
  const c=this.context,duration=Math.min(.42,.1+Math.max(0,strength)*.08),isGlass=kind.includes('glass'),isMetal=kind.includes('metal'),isWood=kind.includes('wood'),gain=c.createGain(),source=c.createBufferSource(),filter=c.createBiquadFilter();source.buffer=this.noise;filter.type=isGlass?'highpass':isMetal?'bandpass':isWood?'lowpass':'lowpass';filter.frequency.value=isGlass?1500:isMetal?850:isWood?430:260;filter.Q.value=isGlass?2.5:isMetal?3:.7;gain.gain.setValueAtTime(.001,c.currentTime);gain.gain.exponentialRampToValueAtTime(Math.min(.28,atten*.4*Math.max(.35,strength)),c.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);source.connect(filter).connect(gain).connect(this.master);this.voices.add(source);this.stats.played++;this.stats.active=this.voices.size;
  const ring=c.createOscillator(),ringGain=c.createGain();ring.type=isGlass?'triangle':isMetal?'sine':'sine';ring.frequency.value=isGlass?1250:isMetal?210:48;ring.detune.value=isGlass?Math.random()*80-40:Math.random()*24-12;ringGain.gain.setValueAtTime(.001,c.currentTime);ringGain.gain.exponentialRampToValueAtTime(Math.min(isGlass?.14:isMetal?.1:.12,atten*.18*Math.max(.35,strength)),c.currentTime+.006);ringGain.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);ring.connect(ringGain).connect(this.master);this.voices.add(ring);this.stats.active=this.voices.size;ring.start();ring.stop(c.currentTime+duration);
  let cleaned=false;const cleanup=()=>{if(cleaned)return;cleaned=true;this.voices.delete(source);this.voices.delete(ring);this.stats.active=this.voices.size;source.disconnect();filter.disconnect();gain.disconnect();ring.disconnect();ringGain.disconnect();};source.onended=cleanup;ring.onended=cleanup;source.start();source.stop(c.currentTime+duration);
 }
 async preview(){await this.unlock();if(!this.enabled||this.context?.state!=='running')return false;this.lastByKind.delete('concrete');this.emit('concrete',{x:0,y:0,z:0},{position:{x:0,y:0,z:0}},1.5);return true;}
 update(){if(this.context?.state==='running'&&this.master)this.master.gain.setTargetAtTime(this.enabled?this.volume:0,this.context.currentTime,.02);}
 reset(){this.lastByKind.clear();for(const voice of this.voices){try{(voice as OscillatorNode|AudioBufferSourceNode).stop();}catch{}voice.disconnect();}this.voices.clear();this.stats.active=0;}
 private suspend(){this.reset();if(this.context?.state==='running')void this.context.suspend().catch(()=>undefined);}
}
