import {TOUCH} from 'three';
import type {GameScene} from './scene';
import type {VehicleWorkshop} from './vehicle-workshop';
import './mobile.css';

type State={scenario:string;sim:unknown;placing:boolean;selected:boolean;walking?:boolean;vehicle:VehicleWorkshop|undefined;demo:boolean};
export function installMobileUI(scene:GameScene,getState:()=>State,fire:()=>Promise<void>,place:()=>void){
 const $=(id:string)=>document.getElementById(id)!;
 const button=(id:string,label:string,help:string)=>{const b=document.createElement('button');b.type='button';b.id=id;b.textContent=label;b.dataset.help=help;return b;};
 const media=matchMedia('(pointer: coarse), (max-width: 700px)');
 const top=document.querySelector('.topbar')!,stage=document.querySelector('.stage')!,sidebar=document.querySelector('.sidebar')!;
 const views=document.querySelector('.view-tools')!,buildStats=document.querySelector('.build-stats')!,settings=document.querySelector('.simulation-settings')!,footer=document.querySelector('.controlbar')!;
 const modes=document.createElement('select');modes.id='mobile-mode';modes.setAttribute('aria-label','Spielmodus');modes.dataset.help='Wählt Sandbox, Herausforderungen oder Demo.';
 for(const [id,name] of [['sandbox-mode','Sandbox'],['campaign-mode','Herausforderungen'],['show-demo','Demo']])modes.add(new Option(name,id));
 modes.onchange=()=>{clearInput();document.body.classList.remove('mobile-tools-open','mobile-menu-open');$(modes.value).click();};top.append(modes);
 const menu=button('mobile-menu','⋯','Öffnet Speichern, Export, Import und Spielanleitung.');menu.onclick=()=>document.body.classList.toggle('mobile-menu-open');top.append(menu);
 const closeTools=button('mobile-tools-close','Fertig ✓','Schließt die Werkzeuge und zeigt wieder die ganze Spielwelt.');closeTools.onclick=()=>document.body.classList.remove('mobile-tools-open');sidebar.prepend(closeTools);
 const tools=$('toggle-panels'),oldTools=tools.onclick;tools.onclick=e=>{if(media.matches)document.body.classList.toggle('mobile-tools-open');else oldTools?.call(tools,e);};
 const world=$('world-controls'),oldWorld=world.onclick;world.onclick=e=>{if(media.matches){clearInput();document.body.classList.toggle('mobile-tools-open');}else oldWorld?.call(world,e);};
 const actions=document.createElement('div');actions.id='mobile-actions';
 const set=button('mobile-place','＋ Setzen','Platziert das gewählte Bauteil an der Vorschau. Tippe zuerst auf einen Platz in der Welt.'),del=button('mobile-delete','⌫','Entfernt das ausgewählte Bauteil. Rückgängig stellt es wieder her.'),help=button('mobile-help','?','Hilfemodus: Danach ein Bedienelement antippen, um seine Erklärung zu lesen, ohne es auszulösen.'),camera=button('mobile-camera','↻ Drehen','Ein Finger dreht die Kamera. Umschalten auf Verschieben; mit zwei Fingern kannst du immer verschieben und zoomen.');help.dataset.mobileHelp='true';
 let pan=false;
 camera.onclick=()=>{pan=!pan;camera.textContent=pan?'↔ Schieben':'↻ Drehen';configureCamera();};
 set.onclick=()=>{if(getState().placing)place();};del.onclick=()=>{$('delete').click();refresh();};
 actions.append(camera,del,set,help);stage.append(actions);
 const gestureHint=document.createElement('div');gestureHint.id='mobile-gesture-hint';stage.append(gestureHint);
 const drive=document.createElement('div');drive.id='mobile-drive';
 const stick=document.createElement('div');stick.className='touch-stick';stick.setAttribute('role','group');stick.setAttribute('aria-label','Fahren und Lenken');stick.dataset.help='Daumen nach oben: vorwärts, unten: rückwärts; links und rechts: lenken. Loslassen beendet den Antrieb. Rechts im Bild wischen: zielen.';stick.innerHTML='<span class="touch-stick-label">FAHREN</span><span class="touch-knob"></span>';
 const brake=button('mobile-brake','■ Bremse','Gedrückt halten, um das Fahrzeug zu bremsen.'),cannon=button('mobile-cannon','● Feuer','Gedrückt halten, um mit den Fahrzeugkanonen zu feuern. Zum Zielen rechts über die Welt wischen.'),reset=button('mobile-drive-reset','↻ Welt','Setzt die gesamte Welt zurück und startet dich wieder im Fahrzeug.');reset.onclick=()=>{clearInput();$('restart').click();};drive.append(stick,brake,cannon,reset);stage.append(drive);
 const erase=button('mobile-vehicle-erase','⌫ Löschen','Löschwerkzeug ein- oder ausschalten. Danach ein Fahrzeugteil in der 3D-Ansicht oder im 2D-Raster antippen.');erase.onclick=()=>{const v=getState().vehicle;if(v){v.touchErase=!v.touchErase;erase.classList.toggle('active',v.touchErase);erase.setAttribute('aria-pressed',String(v.touchErase));}};document.querySelector('#vehicle-tools')!.after(erase);
 const stats=button('mobile-vehicle-stats','Werte & Bauplan','Öffnet die Fahrzeugwerte, Bauprüfung, den 2D-Bauplan sowie Rückgängig und Löschen.');stats.onclick=()=>document.body.classList.toggle('mobile-vehicle-stats-open');document.querySelector('.vehicle-inspector')!.prepend(stats);
 for(const dialog of Array.from(document.querySelectorAll('dialog'))){const b=button('','?','Hilfemodus: Danach das gewünschte Bedienelement antippen.');b.removeAttribute('id');b.className='mobile-dialog-help';b.dataset.mobileHelp='true';(dialog.querySelector('.game-options-heading,.vehicle-dialog-heading')??dialog).append(b);}
 let helpMode=false,blockedPointer:number|undefined,blockedClick=false;
 const setHelp=(value:boolean)=>{helpMode=value;document.body.classList.toggle('touch-help',value);document.querySelectorAll<HTMLElement>('[data-mobile-help]').forEach(b=>b.setAttribute('aria-pressed',String(value)));};
 document.querySelectorAll<HTMLButtonElement>('[data-mobile-help]').forEach(b=>b.onclick=()=>{clearInput();setHelp(!helpMode);});
 window.addEventListener('pointerdown',e=>{blockedClick=false;if(!media.matches||!helpMode||!(e.target instanceof Element)||e.target.closest('[data-mobile-help]'))return;const target=e.target.closest<HTMLElement>('[data-help]');if(!target)return;e.preventDefault();e.stopImmediatePropagation();blockedPointer=e.pointerId;blockedClick=true;setHelp(false);document.dispatchEvent(new CustomEvent('help-request',{detail:target}));},true);
 window.addEventListener('pointerup',e=>{if(e.pointerId===blockedPointer){e.preventDefault();e.stopImmediatePropagation();blockedPointer=undefined;}},true);
 window.addEventListener('click',e=>{if(blockedClick){blockedClick=false;e.preventDefault();e.stopImmediatePropagation();}},true);
 // Existing buttons retain their real handlers; choosing a part just dismisses the sheet.
 document.addEventListener('click',e=>{if(!media.matches||!(e.target instanceof Element)||helpMode)return;if(e.target.closest('[data-part],[data-prefab],[data-vehicle-preset]')){document.body.classList.remove('mobile-tools-open');pickCenter();refresh();}if(e.target.closest('[data-vehicle-part]')){const v=getState().vehicle;if(v)v.touchErase=false;erase.classList.remove('active');}if(e.target.closest('#load-showcase,#generate-building,#reference,#clear'))document.body.classList.remove('mobile-tools-open');});
 function configureCamera(){scene.controls.touches.ONE=pan?TOUCH.PAN:TOUCH.ROTATE;scene.controls.touches.TWO=TOUCH.DOLLY_PAN;}
 function pickCenter(){const r=scene.container.getBoundingClientRect();scene.pick(new PointerEvent('pointermove',{clientX:r.x+r.width/2,clientY:r.y+r.height/2}),false);if(scene.ghost)scene.ghost.visible=true;}
 type Finger={x:number;y:number;startX:number;startY:number;started:number;moved:boolean;multi:boolean};const fingers=new Map<number,Finger>(),touches=new Set<number>();
 window.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;if(e.isPrimary)touches.clear();touches.add(e.pointerId);if(touches.size>1)for(const f of fingers.values())f.multi=true;},true);
 for(const type of ['pointerup','pointercancel'])window.addEventListener(type,e=>touches.delete((e as PointerEvent).pointerId),true);let stickPointer:number|undefined;
 function clearInput(){getState().vehicle?.clearTouchControls();stickPointer=undefined;stick.querySelector<HTMLElement>('.touch-knob')!.style.transform='translate(0px,0px)';fingers.clear();touches.clear();brake.classList.remove('active');cannon.classList.remove('active');}
 const enabled=()=>media.matches&&!getState().walking&&!getState().demo&&!document.querySelector('dialog[open]');
 const setDrive=(input:Parameters<VehicleWorkshop['setTouchControls']>[0])=>{if(enabled()&&getState().vehicle?.driving)getState().vehicle!.setTouchControls(input);};
 const stickMove=(e:PointerEvent)=>{const r=stick.getBoundingClientRect(),radius=r.width*.32,dx=e.clientX-r.x-r.width/2,dy=e.clientY-r.y-r.height/2,scale=Math.min(1,radius/Math.max(1,Math.hypot(dx,dy))),x=dx*scale/radius,y=dy*scale/radius;stick.querySelector<HTMLElement>('.touch-knob')!.style.transform=`translate(${x*radius}px,${y*radius}px)`;setDrive({steer:-Math.sign(x)*Math.pow(Math.max(0,(Math.abs(x)-.18)/.82),1.7)*.6,throttle:Math.abs(y)<.12?0:-y});};
 stick.addEventListener('pointerdown',e=>{if(!enabled()||stickPointer!==undefined)return;e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);});
 stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();stickMove(e);}});
 const stickEnd=(e:PointerEvent)=>{if(e.pointerId!==stickPointer)return;stickPointer=undefined;stick.querySelector<HTMLElement>('.touch-knob')!.style.transform='translate(0px,0px)';setDrive({throttle:0,steer:0});};for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,stickEnd as EventListener);
 const heldButton=(b:HTMLButtonElement,key:'brake'|'fire')=>{let pointer:number|undefined;b.addEventListener('pointerdown',e=>{if(!enabled())return;e.preventDefault();pointer=e.pointerId;b.setPointerCapture(e.pointerId);b.classList.add('active');setDrive({[key]:true});});const end=(e:PointerEvent)=>{if(pointer!==e.pointerId)return;pointer=undefined;b.classList.remove('active');setDrive({[key]:false});};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,end as EventListener);};heldButton(brake,'brake');heldButton(cannon,'fire');
 const viewport=scene.container;
 viewport.addEventListener('pointerdown',e=>{if(!enabled()||(e.pointerType==='mouse'&&e.button!==0))return;const state=getState(),f:Finger={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,started:e.timeStamp,moved:false,multi:touches.size>1};for(const old of fingers.values())old.multi=true;fingers.set(e.pointerId,f);if(state.vehicle?.driving){e.preventDefault();e.stopImmediatePropagation();viewport.setPointerCapture(e.pointerId);state.vehicle.touchDriving=true;}else configureCamera();},true);
 viewport.addEventListener('pointermove',e=>{const f=fingers.get(e.pointerId);if(!f)return;const dx=e.clientX-f.x,dy=e.clientY-f.y;f.moved ||=Math.hypot(e.clientX-f.startX,e.clientY-f.startY)>12;f.x=e.clientX;f.y=e.clientY;if(getState().vehicle?.driving){e.preventDefault();e.stopImmediatePropagation();getState().vehicle!.touchLook(dx,dy);}},true);
 const endWorld=(e:PointerEvent)=>{const f=fingers.get(e.pointerId);if(!f)return;fingers.delete(e.pointerId);const s=getState(),tap=e.type==='pointerup'&&!f.moved&&!f.multi&&Math.hypot(e.clientX-f.startX,e.clientY-f.startY)<=12,quick=tap&&e.timeStamp-f.started<=320;if(s.vehicle?.driving){e.preventDefault();e.stopImmediatePropagation();if(quick&&enabled()){s.vehicle.setTouchControls({fire:true});s.vehicle.setTouchControls({fire:false});}return;}if(tap){const placing=!!s.placing;const shooting=quick&&enabled()&&s.scenario==='sandbox'&&!placing&&document.body.dataset.sandboxTab==='projectiles';if(placing||s.scenario==='sandbox'&&document.body.dataset.sandboxTab==='projectiles')scene.pick(e,false);else scene.pick(e,true);if(scene.ghost)scene.ghost.visible=true;if(shooting)void fire();}refresh();};viewport.addEventListener('pointerup',endWorld,true);viewport.addEventListener('pointercancel',endWorld,true);viewport.addEventListener('lostpointercapture',e=>fingers.delete(e.pointerId),true);
 window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput();});window.addEventListener('orientationchange',()=>{clearInput();scene.resize();});
 let previous='';
 function refresh(){const s=getState();gestureHint.textContent=s.placing?'Platz antippen → Vorschau · Mit Setzen bestätigen':'1 Finger: '+(pan?'Verschieben':'Drehen')+' · 2 Finger: Zoom / Verschieben'+(s.scenario==='sandbox'&&document.body.dataset.sandboxTab==='projectiles'?' · Kurz tippen: Schuss':'');document.body.classList.toggle('mobile-ui',media.matches);document.body.dataset.touchPlacement=String(!!s.placing);document.body.dataset.touchSelection=String(!!s.selected&&!s.placing);actions.hidden=!!s.walking||!media.matches||!!s.vehicle?.driving||s.demo;drive.hidden=!media.matches||!s.vehicle?.driving||s.demo;set.hidden=!s.placing;del.hidden=!s.selected||s.placing;
  if(media.matches){if(views.parentElement!==sidebar)sidebar.append(views);if(buildStats.parentElement!==sidebar)sidebar.append(buildStats);if(settings.parentElement!==sidebar)sidebar.append(settings);scene.container.dataset.help=s.vehicle?.driving?'Ein Finger über die Welt: Kamera und Kanone ausrichten. Kurz antippen: Kanonenschuss. Links steuern, rechts feuern und bremsen.':'Ein Finger dreht oder verschiebt die Ansicht. Zwei Finger zoomen und verschieben. In der Sandbox kurz antippen zum Schießen; Ziehen und Mehrfinger-Gesten schießen nicht. Zum Bauen auf einen Platz tippen und mit Setzen bestätigen.';}else{if(views.parentElement!==stage)stage.append(views);if(buildStats.parentElement!==footer)footer.prepend(buildStats);if(settings.parentElement!==footer)buildStats.after(settings);delete scene.container.dataset.help;}
  const signature=`${media.matches}:${s.scenario}:${!!s.vehicle?.driving}:${s.demo}`;if(signature!==previous){previous=signature;clearInput();document.body.classList.remove('mobile-tools-open','mobile-menu-open','mobile-vehicle-stats-open');setHelp(false);}const active=document.querySelector<HTMLButtonElement>('.primary-modes button.active');modes.value=s.demo?'show-demo':active?.id??'campaign-mode';if(!media.matches){if(getState().vehicle)getState().vehicle!.touchDriving=false;for(const c of ['mobile-tools-open','mobile-menu-open'])if(document.body.classList.contains(c))document.body.classList.remove(c);}if(media.matches)configureCamera();}
 const observe=new MutationObserver(records=>{if(records.some(r=>r.attributeName==='open'))clearInput();refresh();});observe.observe(document.body,{attributes:true,attributeFilter:['data-game-state']});for(const d of Array.from(document.querySelectorAll('dialog')))observe.observe(d,{attributes:true,attributeFilter:['open']});
 media.addEventListener('change',()=>{refresh();scene.resize();});scene.ready.then(()=>{refresh();scene.resize();});refresh();return {refresh};
}
