import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { VEHICLE_PRESETS, vehiclePower, VEHICLE_PARTS, validateVehicle, type VehiclePart } from './vehicle-blueprint';

export const vehicleNames={frame:'Rahmen',wheel:'Rad',engine:'Motor',cannon:'Kanone',armor:'Panzerplatte'};
export function vehicleVisual(kind:string,size?:number[]){
 const root=new THREE.Group(),material=(color:string,metalness=.25)=>new THREE.MeshStandardMaterial({color,roughness:.6,metalness});
 const box=(dimensions:number[],p:number[],color:string)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...dimensions as [number,number,number]),material(color));m.position.set(...p as [number,number,number]);m.castShadow=true;root.add(m);return m};
 if(kind==='wheel'){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.36,20),material('#26343c',.05));wheel.rotation.z=Math.PI/2;root.add(wheel);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.24,.24,.39,12),material('#abc9d5',.8));hub.rotation.z=Math.PI/2;root.add(hub);}
 else if(kind==='cannon'){box([.8,.35,.8],[0,0,0],'#385a6b');const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.12,.17,1.8,12),material('#263e4e',.8));barrel.rotation.x=Math.PI/2;barrel.position.set(0,.23,-.8);root.add(barrel);box([.46,.35,.6],[0,.2,0],'#779aa7');}
 else if(kind==='engine'){box(size??[.8,.65,.8],[0,0,0],'#bc783e');for(let x=-.25;x<=.25;x+=.125)box([.045,.07,.65],[x,.35,0],'#283f4b');}
 else if(kind==='armor')box(size??[.95,.25,.95],[0,0,0],'#88b3c5');
 else{box(size??[.95,.24,.95],[0,0,0],'#416579');box([.75,.035,.55],[0,.14,0],'#77acbe');}
 return root;
}

export function vehicleAssembly(parts:VehiclePart[],wheels=true){const group=new THREE.Group();for(const p of parts){if(p.kind==='wheel'&&!wheels)continue;const mesh=vehicleVisual(p.kind);mesh.position.set(...p.p);mesh.userData.vehicleKind=p.kind;group.add(mesh);}
 for(let i=0;i<parts.length;i++)for(let j=i+1;j<parts.length;j++){const a=parts[i],b=parts[j],from=new THREE.Vector3(...a.p),to=new THREE.Vector3(...b.p),delta=to.clone().sub(from),length=delta.length();if(length>.01&&length<=1.05){const beam=new THREE.Mesh(new THREE.BoxGeometry(.14,length,.14),new THREE.MeshStandardMaterial({color:'#365263',metalness:.55,roughness:.5}));beam.position.copy(from.add(to).multiplyScalar(.5));beam.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());group.add(beam);}}
 return group;}

export class VehicleWorkshop{
 mouseSensitivity=1;invertMouseY=false;
 parts:VehiclePart[]=[]; driving=false; enabled=false; touchDriving=false; touchErase=false; keys=new Set<string>();yaw=0;pitch=.08;private touch={throttle:0,steer:0,brake:false,fire:false};private touchPointers=new Map<number,[number,number]>();private previewTouchMoved=false;private previewTouchMulti=false;private lastHeading:number|undefined;private fireUntil=0;private tool:VehiclePart['kind']='frame';private level=0;private nextId=1;private history:VehiclePart[][]=[];
 private dialog:HTMLDialogElement;private preview=new THREE.Scene();private renderer:THREE.WebGLRenderer;private camera=new THREE.PerspectiveCamera(40,1,.1,100);private controls:OrbitControls;private group=new THREE.Group();private raf=0;
 private session:'idle'|'editing'|'driving'='idle';private blueprintSave:((parts:VehiclePart[],label:string)=>Promise<void>|void)|undefined;private blueprintCancel:(()=>void)|undefined;private blueprintLabel='Dein Fahrzeug';
 constructor(private hooks:{drive:(parts:VehiclePart[])=>Promise<void>;edit:()=>void;send:(input:any)=>void;mode:()=>void;leave:()=>void}){
  const panel=document.createElement('section');panel.id='vehicle-panel';panel.hidden=true;panel.innerHTML=`<span class="eyebrow">FAHRZEUGWERKSTATT</span><p>Baue dein Fahrzeug. Fahre ins Abbruchgelände.</p><select id="vehicle-preset" aria-label="Fertiges Fahrzeug"></select><button id="vehicle-quick" class="primary">▶ Schnellstart</button><button id="vehicle-edit">Fahrzeug bauen / bearbeiten</button>`;document.querySelector('.scenario-section')!.after(panel);
  const button=document.createElement('button');button.id='vehicle-mode';button.textContent='Fahrzeuge';document.querySelector('#workshop-tabs')!.append(button);button.onclick=()=>{this.hooks.mode();this.enabled=true;panel.hidden=false;this.open();};
  this.dialog=document.createElement('dialog');this.dialog.id='vehicle-dialog';this.dialog.innerHTML=`<div class="vehicle-dialog-heading"><div><span class="eyebrow">MODULAR MOTOR WORKS</span><h2>Deine Maschine.</h2></div><button id="vehicle-close" aria-label="Werkstatt schließen">✕</button></div><div class="vehicle-editor"><div><div id="vehicle-tools"></div><label>BAUEBENE <select id="vehicle-level"><option value="0">Fahrgestell</option><option value="1">Aufbau +1 m</option><option value="2">Aufbau +2 m</option></select></label><p class="vehicle-grid-hint">▲ VORNE · Klick setzt / ersetzt · Rechtsklick entfernt</p><div id="vehicle-grid"></div><div class="vehicle-edit-actions"><button id="vehicle-undo">Rückgängig</button><button id="vehicle-empty">Leer beginnen</button></div></div><div class="vehicle-preview-column"><div id="vehicle-preview"></div><p id="vehicle-summary"></p><p id="vehicle-validation" role="status"></p><button id="vehicle-drive" class="primary">Fahren & zerstören →</button><small>WASD fahren · Maus zielen · Linksklick feuern · Leertaste bremsen · R Neustart · Esc Maus lösen</small></div></div>`;document.body.append(this.dialog);
  const hud=document.createElement('div');hud.id='vehicle-hud';hud.hidden=true;hud.innerHTML=`<span class="eyebrow">FAHRZEUGKONTROLLE</span><strong id="vehicle-speed">0 km/h</strong><span id="vehicle-aim">Kanone bereit</span><small>WASD fahren · Maus umsehen & zielen<br>Linksklick / F feuern · Leertaste bremsen</small><button id="vehicle-return">Werkstatt · Esc</button>`;document.querySelector('.stage')!.append(hud);
  const presets=document.querySelector<HTMLSelectElement>('#vehicle-preset')!;presets.innerHTML=VEHICLE_PRESETS.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');presets.onchange=()=>{if(this.driving)this.hooks.edit();this.loadPreset(presets.value);};
  document.querySelector('#vehicle-tools')!.innerHTML=Object.entries(vehicleNames).map(([kind,name])=>`<button data-vehicle-part="${kind}">${name}</button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-vehicle-part]').forEach(b=>b.onclick=()=>{this.tool=b.dataset.vehiclePart as VehiclePart['kind'];this.renderGrid();});
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(500,360);document.querySelector('#vehicle-preview')!.append(this.renderer.domElement);this.preview.add(new THREE.HemisphereLight('#f0faff','#55738a',3));const sun=new THREE.DirectionalLight('#fff1d5',3);sun.position.set(4,8,5);this.preview.add(sun,this.group,new THREE.GridHelper(10,10,'#6898b0','#bbd9e7'));this.camera.position.set(7,7,9);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(0,1,0);
  const previewCanvas=this.renderer.domElement,ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=[0,0];
  const placementGhost=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshBasicMaterial({color:'#2799d1',transparent:true,opacity:.32,depthWrite:false}));placementGhost.visible=false;this.preview.add(placementGhost);
  previewCanvas.addEventListener('pointerleave',()=>{placementGhost.visible=false;});
  previewCanvas.addEventListener('pointermove',e=>{const rect=previewCanvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,this.camera);const hit=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-(.8+this.level)),new THREE.Vector3());if(!hit){placementGhost.visible=false;return;}const x=Math.round(hit.x),z=Math.round(hit.z);placementGhost.visible=Math.abs(x)<=3&&Math.abs(z)<=4;placementGhost.position.set(x,.8+this.level,z);placementGhost.scale.set(...VEHICLE_PARTS[this.tool].size);});
  previewCanvas.addEventListener('contextmenu',e=>e.preventDefault());
  previewCanvas.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];if(e.pointerType==='touch'){if(this.touchPointers.size)this.previewTouchMulti=true;else{this.previewTouchMoved=false;this.previewTouchMulti=false;}this.touchPointers.set(e.pointerId,[e.clientX,e.clientY]);}});
  previewCanvas.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')return;const start=this.touchPointers.get(e.pointerId);if(start&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>6)this.previewTouchMoved=true;});
  previewCanvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch'){this.touchPointers.delete(e.pointerId);if(this.touchPointers.size||this.previewTouchMoved||this.previewTouchMulti)return;}if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>4||(!['touch'].includes(e.pointerType)&&![0,2].includes(e.button)))return;const rect=previewCanvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,this.camera);const hit=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-(.8+this.level)),new THREE.Vector3());if(!hit)return;const x=Math.round(hit.x),z=Math.round(hit.z);if(Math.abs(x)>3||Math.abs(z)>4)return;const old=this.parts.find(p=>p.p[0]===x&&p.p[2]===z&&Math.round(p.p[1]-.8)===this.level),erase=e.button===2||this.touchErase;if(erase&&!old)return;this.checkpoint();this.parts=this.parts.filter(p=>p!==old);if(!erase&&this.parts.length<80)this.parts.push({id:this.nextId++,kind:this.tool,p:[x,.8+this.level,z]});this.refresh();});
  previewCanvas.addEventListener('pointercancel',e=>{this.touchPointers.delete(e.pointerId);this.previewTouchMoved=true;});

  document.querySelector<HTMLSelectElement>('#vehicle-level')!.onchange=e=>{this.level=Number((e.target as HTMLSelectElement).value);this.renderGrid();};
 document.querySelector<HTMLButtonElement>('#vehicle-edit')!.onclick=()=>this.open();document.querySelector<HTMLButtonElement>('#vehicle-quick')!.onclick=()=>void this.drive();document.querySelector<HTMLButtonElement>('#vehicle-drive')!.onclick=()=>this.blueprintSave?this.saveBlueprint():void this.drive();document.querySelector<HTMLButtonElement>('#vehicle-return')!.onclick=()=>this.open();document.querySelector<HTMLButtonElement>('#vehicle-close')!.onclick=()=>this.close();this.dialog.oncancel=e=>{e.preventDefault();this.close();};
  document.querySelector<HTMLButtonElement>('#vehicle-undo')!.onclick=()=>{const last=this.history.pop();if(last){this.parts=last;this.refresh();}};document.querySelector<HTMLButtonElement>('#vehicle-empty')!.onclick=()=>{this.checkpoint();this.parts=[];this.refresh();};
  let savedRaw:string|null=null;try{savedRaw=localStorage.getItem('loadbearing.vehicle');}catch{}this.loadPreset(VEHICLE_PRESETS[2].id);presets.value=VEHICLE_PRESETS[2].id;try{const saved=JSON.parse(savedRaw??'null');if(Array.isArray(saved)&&saved.length<=80&&saved.every(p=>p.kind in vehicleNames&&Array.isArray(p.p)&&p.p.length===3&&p.p.every(Number.isFinite))){this.parts=saved;this.nextId=Math.max(0,...saved.map(p=>p.id))+1;this.refresh();}}catch{}
  window.addEventListener('keydown',e=>{if(document.body.classList.contains('demo-running')||!this.driving||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(['KeyW','KeyA','KeyS','KeyD','Space','KeyF','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Escape'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.code==='Escape'){if(document.pointerLockElement)document.exitPointerLock();else{this.stopDriving();this.hooks.leave();}}else{this.keys.add(e.code);if(e.code==='KeyF')this.fireUntil=performance.now()+120;this.sendControls();}}},true);
  const viewport=document.getElementById('viewport')!;
  viewport.addEventListener('pointerdown',e=>{if(!this.driving||e.pointerType==='touch'||document.body.classList.contains('world-panel-open'))return;e.preventDefault();e.stopImmediatePropagation();if(document.pointerLockElement===viewport){if(e.button===0){this.keys.add('MouseFire');this.fireUntil=performance.now()+120;}}else if(e.button===0){void viewport.requestPointerLock()?.catch(()=>{});}},true);
  viewport.addEventListener('pointerup',e=>{if(e.pointerType==='touch')return;if(this.driving)e.stopImmediatePropagation();this.keys.delete('MouseFire');},true);
  window.addEventListener('mouseup',()=>this.keys.delete('MouseFire'));
  window.addEventListener('mousemove',e=>{if(document.body.classList.contains('demo-running')||!this.driving||document.querySelector('dialog[open]')||document.pointerLockElement!==viewport)return;this.touchLook(e.movementX,e.movementY);});
  document.addEventListener('pointerlockchange',()=>{this.keys.clear();this.lastHeading=undefined;});
  window.addEventListener('keyup',e=>{if(this.keys.delete(e.code)&&this.driving)this.sendControls();});window.addEventListener('blur',()=>{this.keys.clear();this.clearTouchControls();});document.addEventListener('visibilitychange',()=>{if(document.hidden)this.clearTouchControls();});
 }
 private checkpoint(){this.history.push(structuredClone(this.parts));if(this.history.length>40)this.history.shift();}
 loadPreset(id:string){const preset=VEHICLE_PRESETS.find(p=>p.id===id)!;this.parts=structuredClone(preset.parts);this.nextId=Math.max(0,...this.parts.map(p=>p.id))+1;this.refresh();}
 private showEditor(){if(this.dialog.open)this.dialog.close();this.dialog.showModal();this.refresh();const render=()=>{if(!this.dialog.open)return;const box=document.querySelector('#vehicle-preview')!.getBoundingClientRect();this.renderer.setSize(box.width,box.height,false);this.camera.aspect=box.width/box.height;this.camera.updateProjectionMatrix();this.controls.update();this.renderer.render(this.preview,this.camera);this.raf=requestAnimationFrame(render);};cancelAnimationFrame(this.raf);render();}
 open(){this.enabled=true;this.session='editing';if(document.pointerLockElement)document.exitPointerLock();this.hooks.edit();this.driving=false;this.keys.clear();this.clearTouchControls();document.querySelector<HTMLElement>('#vehicle-hud')!.hidden=true;this.blueprintSave=undefined;this.blueprintCancel=undefined;this.blueprintLabel='Dein Fahrzeug';this.showEditor();}
 /** Open the editor over the current world. Saving is the only commit point. */
 editBlueprint(parts:VehiclePart[],label:string,onSave:(parts:VehiclePart[],label:string)=>void,onCancel?:()=>void){this.enabled=true;this.session='editing';this.driving=false;this.keys.clear();this.clearTouchControls();if(document.pointerLockElement)document.exitPointerLock();this.parts=structuredClone(parts);this.nextId=Math.max(0,...this.parts.map(p=>p.id))+1;this.blueprintLabel=label||'Fahrzeug';this.blueprintSave=onSave;this.blueprintCancel=onCancel;const drive=document.querySelector<HTMLButtonElement>('#vehicle-drive');if(drive)drive.textContent='Bauplan übernehmen / Platzieren';const heading=this.dialog.querySelector('h2');if(heading)heading.textContent=this.blueprintLabel;document.querySelector<HTMLElement>('#vehicle-hud')!.hidden=true;this.showEditor();}
 private closeEditor(notify=true){if(this.dialog.open)this.dialog.close();cancelAnimationFrame(this.raf);const cancel=this.blueprintCancel;this.blueprintSave=undefined;this.blueprintCancel=undefined;this.session='idle';const drive=document.querySelector<HTMLButtonElement>('#vehicle-drive');if(drive)drive.textContent='Fahren & zerstören →';if(notify)cancel?.();}
 close(){const wasUnified=!!this.blueprintSave||!!this.blueprintCancel;if(wasUnified){const cancel=this.blueprintCancel;this.closeEditor(false);this.disable();cancel?.();return;}this.closeEditor(false);if(!this.driving&&this.enabled){this.disable();this.hooks.leave();}}
 async saveBlueprint(){const error=validateVehicle(this.parts);if(error){document.querySelector('#vehicle-validation')!.textContent=error;return;}const save=this.blueprintSave;if(!save){void this.drive();return;}const parts=structuredClone(this.parts),label=this.blueprintLabel;try{await save(parts,label);this.closeEditor(false);this.disable();}catch(e){document.querySelector('#vehicle-validation')!.textContent=e instanceof Error?e.message:String(e);}}
 startDriving(){this.enabled=true;this.session='driving';this.driving=true;document.body.classList.add('vehicle-driving');this.keys.clear();this.clearTouchControls();document.querySelector<HTMLElement>('#vehicle-hud')!.hidden=false;}
 stopDriving(){if(document.pointerLockElement)document.exitPointerLock();this.keys.clear();this.clearTouchControls();this.driving=false;this.enabled=false;this.session='idle';document.body.classList.remove('vehicle-driving');document.querySelector<HTMLElement>('#vehicle-hud')!.hidden=true;}
 async drive(){document.querySelector('#vehicle-validation')!.textContent='Fahrzeug wird aufgebaut …';try{await this.hooks.drive(structuredClone(this.parts));this.startDriving();this.closeEditor(false);this.keys.clear();document.querySelector<HTMLElement>('#vehicle-hud')!.hidden=false;}catch(e){document.querySelector('#vehicle-validation')!.textContent=e instanceof Error?e.message:String(e);if(!this.dialog.open){this.open();document.querySelector('#vehicle-validation')!.textContent=e instanceof Error?e.message:String(e);}}}
 disable(){this.stopDriving();this.enabled=false;document.querySelector<HTMLElement>('#vehicle-panel')!.hidden=true;}
 private sendControls(){if(document.querySelector('dialog[open]')){this.keys.clear();this.touch={throttle:0,steer:0,brake:false,fire:false};this.touchDriving=false;this.fireUntil=0;this.hooks.send({throttle:0,steer:0,brake:true,fire:false,yaw:this.yaw,pitch:this.pitch});return;}const pressed=(k:string)=>Number(this.keys.has(k));const clamp=(n:number)=>Math.max(-1,Math.min(1,n));this.hooks.send({throttle:clamp(pressed('KeyW')-pressed('KeyS')+this.touch.throttle),steer:clamp(pressed('KeyA')-pressed('KeyD')+this.touch.steer),brake:!!pressed('Space')||this.touch.brake,fire:!!pressed('KeyF')||!!pressed('MouseFire')||this.touch.fire||performance.now()<this.fireUntil,yaw:this.yaw,pitch:this.pitch});}
 setTouchControls(input:Partial<{throttle:number;steer:number;brake:boolean;fire:boolean}>){this.touch={...this.touch,...input};if(input.fire)this.fireUntil=performance.now()+120;this.touchDriving=true;this.sendControls();}
 touchLook(dx:number,dy:number){if(!this.driving)return;this.yaw-=dx*.0025*this.mouseSensitivity;this.pitch=Math.max(-.1,Math.min(.7,this.pitch-dy*.0025*this.mouseSensitivity*(this.invertMouseY?-1:1)));this.sendControls();}
 clearTouchControls(){this.touch={throttle:0,steer:0,brake:false,fire:false};this.fireUntil=0;this.touchDriving=false;if(this.driving||this.enabled)this.sendControls();}
 update(dt:number,speed:number,heading=0){if(!this.driving){this.lastHeading=undefined;return;}
 // Mouse aim stays in world space; convert back to the relative turret yaw.
 if((document.pointerLockElement||this.touchDriving)&&this.lastHeading!==undefined){const delta=heading-this.lastHeading;this.yaw-=Math.atan2(Math.sin(delta),Math.cos(delta));}
 this.lastHeading=heading;const pressed=(k:string)=>Number(this.keys.has(k));this.yaw+=(pressed('ArrowLeft')-pressed('ArrowRight'))*dt;this.pitch=Math.max(-.1,Math.min(.7,this.pitch+(pressed('ArrowUp')-pressed('ArrowDown'))*dt*.5));this.sendControls();document.querySelector('#vehicle-speed')!.textContent=`${Math.round(speed*3.6)} km/h`;document.querySelector('#vehicle-aim')!.textContent=this.parts.some(p=>p.kind==='cannon')?`Kanone · ${Math.round(this.yaw*180/Math.PI)}° / ${Math.round(this.pitch*180/Math.PI)}°`:'Keine Kanone montiert';document.querySelector('#vehicle-hud small')!.innerHTML=document.pointerLockElement?'WASD fahren · Maus zielen · Linksklick feuern<br>Leertaste bremsen · R Neustart · Esc Maus lösen':'Klick ins Spielfeld: Mausblick aktivieren<br>WASD fahren · F feuern · R Neustart · Esc Werkstatt';}
 private renderGrid(){const grid=document.querySelector('#vehicle-grid')!;grid.innerHTML='';for(let z=-4;z<=4;z++)for(let x=-3;x<=3;x++){const p=this.parts.find(p=>Math.round(p.p[0])===x&&Math.round(p.p[2])===z&&Math.round(p.p[1]-.8)===this.level),cell=document.createElement('button');cell.type='button';cell.className='vehicle-cell '+(p?'v-'+p.kind:'');cell.title=`${x}, ${z}: ${p?vehicleNames[p.kind]:'Leer'}`;cell.textContent=p?({frame:'▦',wheel:'◉',engine:'M',cannon:'↟',armor:'▰'}[p.kind]):'·';cell.onclick=()=>{this.checkpoint();this.parts=this.parts.filter(part=>part!==p);if(!this.touchErase&&this.parts.length<80)this.parts.push({id:this.nextId++,kind:this.tool,p:[x,.8+this.level,z]});this.refresh();};cell.oncontextmenu=e=>{e.preventDefault();if(p){this.checkpoint();this.parts=this.parts.filter(part=>part!==p);this.refresh();}};grid.append(cell);}document.querySelectorAll<HTMLElement>('[data-vehicle-part]').forEach(b=>b.classList.toggle('active',b.dataset.vehiclePart===this.tool));}
 private refresh(){const power=vehiclePower(this.parts);this.renderGrid();this.group.traverse((o:any)=>{o.geometry?.dispose();if(o.material)o.material.dispose();});this.group.clear();this.group.add(vehicleAssembly(this.parts));document.querySelector('#vehicle-summary')!.innerHTML=[['Bauteile',this.parts.length],['Räder',this.parts.filter(p=>p.kind==='wheel').length],['Motorverbund',power.connected],['Kanonen',this.parts.filter(p=>p.kind==='cannon').length],['Masse',(this.parts.reduce((sum,p)=>sum+VEHICLE_PARTS[p.kind].mass,0)/1000).toFixed(2)+' t'],['Antriebsziel',Math.round(power.wheelSpeed*.55*3.6)+' km/h']].map(([label,value])=>`<span class="vehicle-stat-row"><span>${label}</span><b>${value}</b></span>`).join('');const error=validateVehicle(this.parts);const validation=document.querySelector<HTMLElement>('#vehicle-validation')!;validation.textContent=error||'✓ Alle Teile verbunden · bereit zum Fahren';validation.classList.toggle('valid',!error);try{localStorage.setItem('loadbearing.vehicle',JSON.stringify(this.parts));}catch{}}
}
