/** Deutsche Kurzbeschreibungen für die Fahrzeugwerkstatt, Fahransicht und Fahrzeugoptionen. */
export const vehicleHelp: Record<string, string> = {
  '#vehicle-panel': 'Hier wählst du ein fertiges Fahrzeug oder öffnest die Werkstatt zum eigenen Aufbau.',
  '#vehicle-mode': 'Wechselt in den Fahrzeugmodus mit Werkstatt, Fahransicht und Zerstörungsstrecke.',
  '#vehicle-preset': 'Lädt ein ausgewähltes vorgefertigtes Fahrzeug; ein eigener Entwurf wird dabei ersetzt.',
  '#vehicle-quick': 'Baut den gewählten Entwurf sofort auf und startet die Fahrt ins Abbruchgelände.',
  '#vehicle-edit': 'Öffnet die Fahrzeugwerkstatt. Klicke in der 3D-Ansicht, um Teile auf der gewählten Ebene zu platzieren, oder nutze den 2D-Bauplan.',
  '#vehicle-dialog': 'In der Werkstatt entsteht dein Fahrzeug aus verbundenen Teilen im 1-m-Raster.',
  '.vehicle-dialog-heading': 'Werkstattkopf mit Fahrzeugtitel, Optionen und Schließen-Schaltfläche.',
  '#vehicle-close': 'Schließt die Werkstatt und löst vorher eine aktive Mausfixierung.',
  '.vehicle-editor': 'Linke Seite: Teile und Bauplan; rechte Seite: 3D-Vorschau und Fahrzeugwerte.',
  '#vehicle-tools': 'Wähle hier den Teiltyp, den ein Klick auf ein freies Rasterfeld platziert.',
  '[data-vehicle-part="frame"]': 'Rahmen bildet das tragende Grundgerüst; alle Teile müssen daran verbunden sein.',
  '[data-vehicle-part="wheel"]': 'Räder bestimmen Antrieb und Lenkung; mindestens vier Räder an zwei Achsen sind nötig.',
  '[data-vehicle-part="engine"]': 'Motoren treiben die Räder an; direkt verbundene Motoren erhöhen Drehmoment und Tempo.',
  '[data-vehicle-part="cannon"]': 'Kanonen feuern mit Linksklick oder F und haben pro Kanone 1,1 Sekunden Abklingzeit.',
  '[data-vehicle-part="armor"]': 'Panzerplatten erhöhen Masse und Rammschaden und machen das Fahrzeug schwerer.',
  '#vehicle-level': 'Wählt die Bauebene: Fahrgestell oder Aufbau in 1 bzw. 2 m Höhe.',
  '.vehicle-grid-hint': 'Klick setzt oder ersetzt ein Teil; Rechtsklick entfernt ein Teil aus dem Raster.',
  '#vehicle-grid': 'Platziere Teile im Raster. Benachbarte Felder verbinden sich, gleiche Positionen sind nicht erlaubt.',
  '.vehicle-edit-actions': 'Änderungen am Bauplan rückgängig machen oder einen leeren Entwurf beginnen.',
  '#vehicle-undo': 'Stellt den letzten gespeicherten Zustand des Bauplans wieder her.',
  '#vehicle-empty': 'Entfernt alle Teile nach einem Sicherungsschritt, damit du frei neu bauen kannst.',
  '.vehicle-preview-column': 'Zeigt eine drehbare 3D-Vorschau, Statistiken, Validierung und den Start der Fahrt.',
  '#vehicle-preview': 'Klick setzt das gewählte Teil auf der Bauebene; Rechtsklick entfernt ein Teil. Ziehen dreht die Ansicht, das Mausrad zoomt.',
  '#vehicle-summary': 'Zeigt Teilezahl, Räder, verbundene Motoren, Kanonen, Masse und Zielgeschwindigkeit.',
  '#vehicle-validation': 'Meldet fehlende oder unverbundene Pflichtteile; nur ein gültiger Bauplan kann fahren.',
  '#vehicle-drive': 'Prüft den Bauplan, baut das Fahrzeug auf und wechselt ins physikalische Abbruchgelände.',
  '#vehicle-hud': 'Fahranzeige mit Geschwindigkeit, Kanonenrichtung und den aktuellen Fahrzeugtasten.',
  '#vehicle-speed': 'Aktuelle Fahrzeuggeschwindigkeit in km/h, aus der Physikgeschwindigkeit berechnet.',
  '#vehicle-aim': 'Zeigt Kanonenwinkel oder weist darauf hin, dass keine Kanone montiert ist.',
  '#vehicle-return': 'Beendet die Fahrt und öffnet wieder die Werkstatt; Esc hat denselben Zweck ohne Mausfixierung.',
  '.vehicle-inspector': 'Inspektor mit den laufenden Fahrzeugwerten und dem ausklappbaren Bauplan.',
  '.vehicle-plan': 'Ausklappbarer 2D-Bauplan: Ebene wählen, Raster bearbeiten und Änderungen zurücknehmen.',
  '.vehicle-preset-label': 'Schnellstart-Auswahl für die drei mitgelieferten Fahrzeugentwürfe.',
  '.vehicle-layer': 'Umschalter für die Höhe, auf der neue Teile im Bauplan platziert werden.',
  '.vehicle-workspace-footer': 'Hinweise zu Speicherung, Platzierung, Entfernen und Drehen der Fahrzeugansicht.',
  '.workshop-options': 'Öffnet die globalen Optionen direkt aus der Fahrzeugwerkstatt.',
  '#game-options-dialog': 'Globale Einstellungen werden lokal gespeichert und sofort auf Szene und Fahrzeug angewendet.',
  '.game-options-heading': 'Optionenkopf mit Titel und Schaltfläche zum Schließen.',
  '.game-options-close': 'Schließt den Optionen-Dialog; Änderungen bleiben bereits lokal gespeichert.',
  '.game-options-intro': 'Informiert darüber, dass diese Einstellungen auf dem aktuellen Gerät gespeichert werden.',
  '.game-options-fields': 'Bündelt Render-, Maus- und Anzeigeoptionen für Spiel und Fahrzeugsteuerung.',
  '#game-options-resolution': '75 % rendert schneller, 100 % entspricht der nativen Auflösung, 150 % liefert ein schärferes Bild.',
  '#game-options-resolution-value': 'Zeigt den aktuell gewählten Renderfaktor als Prozentwert.',
  '#game-options-sensitivity': 'Regelt die Mausbewegung beim Zielen; erlaubt Werte von 0,5× bis 2×.',
  '#game-options-sensitivity-value': 'Zeigt die aktuelle Mausempfindlichkeit als Multiplikator.',
  '#game-options-invert': 'Kehrt die vertikale Mausachse beim Zielen um.',
  '#game-options-hints': 'Blendet die eingeblendeten Tastatur- und Steuerungshinweise ein oder aus.',
  '#game-options-telemetry': 'Zeigt Leistungsdaten wie Rendering- und Simulationswerte in der Oberfläche.',
  '.game-options-check': 'Checkbox für eine sofort wirksame Anzeige- oder Steuerungsoption.',
  '.game-options-debris': 'Enthält die gemeinsam genutzte Einstellung für die maximale aktive Trümmermenge.',
  '.game-options-saved': 'Bestätigt, dass die Änderung lokal gespeichert wurde und sofort gilt.',
};

export const vehiclePartHelp: Record<string, string> = {
  frame: 'Tragender Rahmen: verbindet die Konstruktion und ist der Ausgangspunkt für die Stabilitätsprüfung. Masse: 180 kg.',
  wheel: 'Rad: wird separat physikalisch simuliert und über Motoren angetrieben; mindestens vier Räder auf zwei Achsen sind Pflicht. Masse: 85 kg.',
  engine: 'Motor: direkt verbundene Motoren bilden eine Antriebseinheit und steigern Drehmoment sowie Raddrehzahl. Masse: 400 kg.',
  cannon: 'Kanone: feuert in die Zielrichtung und erzeugt beim Schuss Rückstoß; jede Kanone hat 1,1 s Abklingzeit. Masse: 800 kg.',
  armor: 'Panzerplatte: erhöht Fahrzeugmasse und die Stärke beim Rammen von Bauwerken, ohne selbst Antrieb zu liefern. Masse: 350 kg.',
};
